// ilms-frontend-angular/src/app/features/label-management/components/print-station/print-station.component.ts
import { Component, OnInit, ViewChild } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { MatStepperModule, MatStepper } from '@angular/material/stepper';
import { MatGridListModule } from '@angular/material/grid-list';
import { MatCardModule } from '@angular/material/card';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatTableModule } from '@angular/material/table';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatSelectModule } from '@angular/material/select';
import { MatChipsModule } from '@angular/material/chips';
import { MatProgressBarModule } from '@angular/material/progress-bar';
import { MatTooltipModule } from '@angular/material/tooltip';
import { MatMenuModule } from '@angular/material/menu';
import { MatDividerModule } from '@angular/material/divider';
import { Router } from '@angular/router';
import { LabelService } from '../../services/label.service';
import { LabelPreviewComponent } from '../../../../shared/components/label-preview/label-preview.component';
import { jsPDF } from 'jspdf';

interface OrderLineConfig {
  line: any;
  hierarchy: any | null;
  levels: any[];
  counts: { [levelId: string]: number };
  error?: string;
  needsSelection?: boolean;
  hierarchies?: any[];
}

@Component({
  selector: 'app-print-station',
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    MatStepperModule,
    MatGridListModule,
    MatCardModule,
    MatButtonModule,
    MatIconModule,
    MatTableModule,
    MatFormFieldModule,
    MatInputModule,
    MatSelectModule,
    MatChipsModule,
    MatProgressBarModule,
    MatTooltipModule,
    MatDividerModule,
    MatMenuModule,
    LabelPreviewComponent
  ],
  templateUrl: './print-station.component.html',
  styleUrl: './print-station.component.scss'
})
export class PrintStationComponent implements OnInit {
  @ViewChild('stepper') stepper!: MatStepper;

  orders: any[] = [];
  selectedOrder: any = null;
  orderLines: any[] = [];
  lineConfigs: { [lineId: string]: OrderLineConfig } = {};
  
  loading = false;
  activeStep = 0;

  constructor(private labelService: LabelService, private router: Router) {}

  ngOnInit() {
    this.loadOrders();
  }

  async loadOrders() {
    this.loading = true;
    try {
      let data = await this.labelService.getPendingOrders();
      // Mock data if empty for demo
      if (!data || data.length === 0) {
        data = [
          { id: 'd1', order_number: 'SO-2024-001', customer_name: 'PharmaDist Inc.', created_at: new Date().toISOString(), status: 'PENDING' },
          { id: 'd2', order_number: 'SO-2024-002', customer_name: 'Metro Health Co.', created_at: new Date().toISOString(), status: 'PENDING' }
        ];
      }
      this.orders = data;
    } catch (e) {
      console.error(e);
    }
    this.loading = false;
  }

  async onOrderSelect(order: any) {
    this.loading = true;
    this.selectedOrder = order;
    try {
      let lines = await this.labelService.getOrderLines(order.id);
      
      // Mock lines if empty
      if (!lines || lines.length === 0) {
        lines = [
          { id: 'l1', material_code: 'MAT-AMX', quantity: 100, uom: 'Units', material: { name: 'Amoxicillin 250mg' } },
          { id: 'l2', material_code: 'MAT-INS', quantity: 50, uom: 'Units', material: { name: 'Insulin Glargine' } }
        ];
      }
      this.orderLines = lines;

      // Initialize configs
      const configs: { [lineId: string]: OrderLineConfig } = {};
      for (const line of lines) {
        let hierarchies = await this.labelService.getHierarchies(line.material_code);
        
        if (hierarchies.length === 1) {
          const h = hierarchies[0];
          const levels = await this.labelService.getLevels(h.id);
          configs[line.id] = {
            line,
            hierarchy: h,
            levels: levels.sort((a: any, b: any) => a.level_order - b.level_order),
            counts: this.calculateDefaultCounts(line.quantity, levels)
          };
        } else if (hierarchies.length > 1) {
          configs[line.id] = { line, hierarchy: null, levels: [], counts: {}, needsSelection: true, hierarchies };
        } else {
          configs[line.id] = { line, hierarchy: null, levels: [], counts: {}, error: 'No hierarchy found' };
        }
      }
      this.lineConfigs = configs;
      setTimeout(() => this.stepper.next(), 0);
    } catch (e) {
      console.error(e);
    }
    this.loading = false;
  }

  calculateDefaultCounts(qty: number, levels: any[]) {
    const counts: { [id: string]: number } = {};
    levels.forEach(lvl => {
      const cap = lvl.capacity || 1;
      counts[lvl.id] = Math.ceil(qty / cap);
    });
    return counts;
  }

  updateLevelCount(lineId: string, levelId: string, val: any) {
    if (this.lineConfigs[lineId]) {
      this.lineConfigs[lineId].counts[levelId] = parseInt(val) || 0;
    }
  }

  async selectHierarchyForLine(lineId: string, h: any) {
    this.loading = true;
    try {
      const levels = await this.labelService.getLevels(h.id);
      this.lineConfigs[lineId] = {
        ...this.lineConfigs[lineId],
        hierarchy: h,
        levels: levels.sort((a: any, b: any) => a.level_order - b.level_order),
        counts: this.calculateDefaultCounts(this.lineConfigs[lineId].line.quantity, levels),
        needsSelection: false
      };
    } catch (e) {
      console.error(e);
    }
    this.loading = false;
  }

  getTotalLabelCount() {
    let total = 0;
    Object.values(this.lineConfigs).forEach(c => {
      Object.values(c.counts).forEach(count => total += count);
    });
    return total;
  }

  generatePDF() {
    const doc = new jsPDF();
    doc.setFontSize(20);
    doc.text('SHIPPING LABELS', 105, 20, { align: 'center' });
    
    let y = 40;
    Object.values(this.lineConfigs).forEach(config => {
      config.levels.forEach(lvl => {
        const count = config.counts[lvl.id] || 0;
        for (let i = 0; i < count; i++) {
          if (y > 250) {
            doc.addPage();
            y = 20;
          }
          doc.setDrawColor(0);
          doc.rect(20, y, 170, 40);
          doc.setFontSize(12);
          doc.text(config.line.material?.name || config.line.material_code, 25, y + 10);
          doc.setFontSize(10);
          doc.text(`Level: ${lvl.level_name} | Order: ${this.selectedOrder.order_number}`, 25, y + 20);
          doc.text(`Serial: ${lvl.id.substr(0,8)}-${i+1}`, 25, y+30);
          y += 50;
        }
      });
    });

    doc.save(`Labels_${this.selectedOrder.order_number}.pdf`);
  }

  printAll() {
    window.print();
  }

  finish() {
    this.router.navigate(['/label-management/trade-item']);
  }

  // Helpers for Template
  objectKeys(obj: any): string[] {
    return Object.keys(obj);
  }

  createRange(n: number): number[] {
    return Array.from({ length: n }, (_, i) => i + 1);
  }

  // Dummy Templates for Demo
  amxElements: any[] = [
    { id: '1', type: 'text', x: 10, y: 10, width: 80, height: 10, content: 'AMOXICILLIN 250mg', fontSize: 16, fontWeight: 'bold' },
    { id: '2', type: 'text', x: 10, y: 22, width: 80, height: 10, content: 'Code: {materialCode}', fontSize: 10 },
    { id: '3', type: 'barcode', x: 10, y: 40, width: 80, height: 30, content: '{materialCode}-{serialNumber}' },
    { id: '4', type: 'qr', x: 65, y: 80, width: 25, height: 25, content: '{serialNumber}' },
    { id: '5', type: 'text', x: 10, y: 80, width: 50, height: 10, content: 'BATCH: {batchNumber}', fontSize: 10 }
  ];

  insElements: any[] = [
    { id: '1', type: 'text', x: 10, y: 10, width: 80, height: 10, content: 'INSULIN GLARGINE', fontSize: 16, fontWeight: 'bold' },
    { id: '2', type: 'text', x: 10, y: 22, width: 80, height: 10, content: 'Cold Chain: 2-8°C', fontSize: 10, fontWeight: 'bold' },
    { id: '3', type: 'qr', x: 10, y: 40, width: 40, height: 40, content: 'INS-{serialNumber}' },
    { id: '4', type: 'barcode', x: 10, y: 90, width: 80, height: 20, content: '{materialCode}' }
  ];
}

<div class="print-station-container no-print">
  <div class="header">
    <div class="title-group">
      <h1>Shipping Label Generator</h1>
      <p>Fulfill Sales Orders with Automated Packaging & Label Calculations</p>
    </div>
    <div class="order-chip" *ngIf="selectedOrder">
      <mat-icon>shopping_cart</mat-icon>
      <span>Order: {{selectedOrder.order_number}}</span>
    </div>
  </div>

  <mat-stepper #stepper [linear]="true" class="stepper-main">
    
    <!-- Step 1: Order Selection -->
    <mat-step [editable]="false">
      <ng-template matStepLabel>Order Selection</ng-template>
      <div class="step-content">
        <mat-grid-list cols="12" rowHeight="200px" gutterSize="16px">
          <mat-grid-tile *ngFor="let order of orders" colspan="4">
            <mat-card class="order-card" (click)="onOrderSelect(order)" [class.selected]="selectedOrder?.id === order.id">
              <mat-card-header>
                <div mat-card-avatar class="order-avatar">
                  <mat-icon>shopping_cart</mat-icon>
                </div>
                <mat-card-title>{{order.order_number}}</mat-card-title>
                <mat-card-subtitle>{{order.customer_name}}</mat-card-subtitle>
              </mat-card-header>
              <mat-card-content>
                <div class="card-info">
                  <mat-icon>calendar_today</mat-icon>
                  <span>{{order.created_at | date}}</span>
                </div>
                <mat-chip-set>
                  <mat-chip>{{order.status}}</mat-chip>
                </mat-chip-set>
              </mat-card-content>
            </mat-card>
          </mat-grid-tile>
        </mat-grid-list>
        
        <div class="loading-overlay" *ngIf="loading">
          <mat-progress-bar mode="indeterminate"></mat-progress-bar>
        </div>
      </div>
    </mat-step>

    <!-- Step 2: Configuration -->
    <mat-step>
      <ng-template matStepLabel>Configure Packaging</ng-template>
      <div class="step-content">
        <div *ngFor="let line of orderLines" class="config-row">
          <mat-card class="line-config-card">
            <div class="line-info">
              <div class="label">Material</div>
              <div class="value">{{line.material?.name || line.material_code}}</div>
              <div class="sub-value">Qty: {{line.quantity}} {{line.uom}}</div>
              
              <div class="hierarchy-selector" *ngIf="lineConfigs[line.id]?.needsSelection">
                <button mat-flat-button color="warn" [matMenuTriggerFor]="hMenu">Choose Hierarchy</button>
                <mat-menu #hMenu="matMenu">
                  <button mat-menu-item *ngFor="let h of lineConfigs[line.id].hierarchies" (click)="selectHierarchyForLine(line.id, h)">
                    {{h.name}}
                  </button>
                </mat-menu>
              </div>

              <div class="assigned-hierarchy" *ngIf="lineConfigs[line.id]?.hierarchy">
                <mat-icon>storage</mat-icon>
                <span>{{lineConfigs[line.id].hierarchy.name}}</span>
              </div>
            </div>

            <div class="level-configs">
              <div class="section-title">Label Counts</div>
              <div class="levels-grid">
                <div *ngFor="let lvl of lineConfigs[line.id]?.levels" class="level-input-group">
                  <mat-form-field appearance="outline">
                    <mat-label>{{lvl.level_name}}</mat-label>
                    <input matInput type="number" [ngModel]="lineConfigs[line.id].counts[lvl.id]" (ngModelChange)="updateLevelCount(line.id, lvl.id, $event)">
                    <mat-hint>{{lvl.capacity}} units/pack</mat-hint>
                  </mat-form-field>
                </div>
              </div>
            </div>
          </mat-card>
        </div>

        <div class="actions-row">
          <button mat-button matStepperPrevious>Back</button>
          <button mat-flat-button color="primary" matStepperNext [disabled]="loading">Next: Preview</button>
        </div>
      </div>
    </mat-step>

    <!-- Step 3: Print -->
    <mat-step>
      <ng-template matStepLabel>Preview & Print</ng-template>
      <div class="step-content preview-step">
        <div class="preview-header">
          <div class="stats">
            <mat-icon color="primary">check_circle</mat-icon>
            <span>Ready to generate <strong>{{getTotalLabelCount()}}</strong> labels.</span>
          </div>
          <div class="action-buttons">
            <button mat-stroked-button (click)="generatePDF()">
              <mat-icon>download</mat-icon> Download PDF
            </button>
            <button mat-flat-button color="primary" (click)="printAll()">
              <mat-icon>print</mat-icon> Print Labels
            </button>
          </div>
        </div>

        <div class="label-sheets-preview">
          <div *ngFor="let lineId of objectKeys(lineConfigs)" class="sheet-group">
             <h3>{{lineConfigs[lineId].line.material?.name}}</h3>
             <div class="sheet-grid">
               <ng-container *ngFor="let lvl of lineConfigs[lineId].levels">
                 <div *ngFor="let i of createRange(lineConfigs[lineId].counts[lvl.id])" class="preview-item">
                    <app-label-preview 
                      [width]="101" 
                      [height]="152" 
                      [elements]="lineConfigs[lineId].line.material_code === 'MAT-AMX' ? amxElements : insElements" 
                      [data]="{ materialName: lineConfigs[lineId].line.material?.name, materialCode: lineConfigs[lineId].line.material_code, batchNumber: 'B-2024-X', serialNumber: 'SN-' + i }"
                      [scale]="1.5"
                    ></app-label-preview>
                 </div>
               </ng-container>
             </div>
          </div>
        </div>

        <div class="actions-row">
          <button mat-button matStepperPrevious>Back</button>
          <button mat-flat-button color="accent" (click)="finish()">Finish & Return</button>
        </div>
      </div>
    </mat-step>

  </mat-stepper>
</div>

<!-- Special Printing View (only visible when printing) -->
<div class="print-only">
  <div *ngFor="let lineId of objectKeys(lineConfigs)" class="print-group">
    <ng-container *ngFor="let lvl of lineConfigs[lineId].levels">
      <div *ngFor="let i of createRange(lineConfigs[lineId].counts[lvl.id])" class="print-label-wrapper">
        <app-label-preview 
          [width]="101" 
          [height]="152" 
          [elements]="lineConfigs[lineId].line.material_code === 'MAT-AMX' ? amxElements : insElements" 
          [data]="{ materialName: lineConfigs[lineId].line.material?.name, materialCode: lineConfigs[lineId].line.material_code, batchNumber: 'B-2024-X', serialNumber: 'SN-' + i }"
          [scale]="3.78"
        ></app-label-preview>
      </div>
    </ng-container>
  </div>
</div>

// ilms-frontend/src/components/LabelManagement/Print/PrintStation.jsx
import React, { useState, useEffect } from 'react';
import { useParams, useNavigate, useLocation } from 'react-router-dom';
import {
    Box, Button, Paper, Typography, Stepper, Step, StepLabel,
    Table, TableBody, TableCell, TableContainer, TableHead, TableRow,
    TextField, Chip, Tabs, Tab, Dialog, DialogTitle, DialogContent, DialogActions,
    Alert, LinearProgress, FormControl, InputLabel, Select, MenuItem,
    Divider, Grid, IconButton, Tooltip, Avatar, Card, CardContent, Stack
} from '@mui/material';
import { 
    ArrowBack, CheckCircle, Print, Storage, 
    PlayCircleOutline, ShoppingCart, Business, 
    CalendarMonth, LocalShipping, Edit, Calculate
} from '@mui/icons-material';
import { PackagingAPI, OrdersAPI } from '../../../services/APIService';
import LabelPreview from '../../LabelPreview';
import { jsPDF } from 'jspdf';
import Barcode from 'react-barcode';

export default function ShippingLabelGenerator() {
    const navigate = useNavigate();
    const location = useLocation();
    const [activeStep, setActiveStep] = useState(0);
    const steps = ['Order Selection', 'Configure Packaging', 'Preview & Print'];

    // Data State
    const [orders, setOrders] = useState([]);
    const [loading, setLoading] = useState(false);
    const [selectedOrder, setSelectedOrder] = useState(null);
    const [orderLines, setOrderLines] = useState([]);
    
    // Configuration State
    const [lineConfigs, setLineConfigs] = useState({}); // lineId -> { hierarchy, levels, counts: { levelId: count } }
    const [hierarchyDialog, setHierarchyDialog] = useState({ open: false, line: null, options: [] });

    useEffect(() => {
        loadPendingOrders();
        
        // Handle items passed from Material Inventory
        if (location.state?.preSelectedItems) {
            handlePreSelectedItems(location.state.preSelectedItems);
        }
    }, []);

    const handlePreSelectedItems = async (items) => {
        setLoading(true);
        try {
            // Create a dummy order for these items
            const dummyOrder = { 
                id: 'bulk-print', 
                order_number: 'BULK-PRINT-' + Math.floor(Math.random() * 1000),
                customer_name: 'Internal Label Generation',
                status: 'PROCESSING'
            };
            setSelectedOrder(dummyOrder);
            
            // Format items into order lines
            const lines = items.map(item => ({
                id: 'line-' + item.id,
                material_code: item.material_code,
                material: { name: item.material_name || item.material_code },
                quantity: item.quantity || 1,
                uom: 'Units'
            }));
            setOrderLines(lines);
            
            // Fetch hierarchies/levels for each item
            const configs = {};
            for (const line of lines) {
                let hierarchies = await PackagingAPI.getHierarchies(line.material_code);
                if (hierarchies.length > 0) {
                    const h = hierarchies[0];
                    const levels = await PackagingAPI.getLevels(h.id);
                    configs[line.id] = {
                        hierarchy: h,
                        levels: levels.sort((a,b) => a.level_order - b.level_order),
                        counts: calculateDefaultCounts(line.quantity, levels)
                    };
                }
            }
            setLineConfigs(configs);
            setActiveStep(1); // Skip order selection
        } catch (e) { console.error(e); }
        setLoading(false);
    };

    const loadPendingOrders = async () => {
        setLoading(true);
        try {
            let data = await OrdersAPI.listPending();
            
            // DUMMY DATA FALLBACK
            if (!data || data.length === 0) {
                console.log("Using dummy orders for exploration...");
                data = [
                    { id: 'd1', order_number: 'SO-2024-001', customer_name: 'PharmaDist Inc.', order_date: new Date().toISOString(), status: 'PENDING' },
                    { id: 'd2', order_number: 'SO-2024-002', customer_name: 'Metro Health Co.', order_date: new Date().toISOString(), status: 'PENDING' }
                ];
            }
            
            setOrders(data);
        } catch (e) { console.error(e); }
        setLoading(false);
    };

    const handleOrderSelect = async (order) => {
        setLoading(true);
        setSelectedOrder(order);
        try {
            const lines = await OrdersAPI.getLines(order.id);
            setOrderLines(lines);
            
            // For each line, try to find and auto-assign hierarchy
            const configs = {};
            for (const line of lines) {
                // Try to find hierarchy by material code, or its name (e.g. "Amoxicillin")
                let hierarchies = await PackagingAPI.getHierarchies(line.material_code);
                if (hierarchies.length === 0 && line.material?.name) {
                    const baseName = line.material.name.split(' ')[0]; // Take first word, e.g. "Amoxicillin"
                    hierarchies = await PackagingAPI.getHierarchies(baseName);
                }
                
                if (hierarchies.length === 1) {
                    const h = hierarchies[0];
                    const levels = await PackagingAPI.getLevels(h.id);
                    configs[line.id] = { 
                        hierarchy: h, 
                        levels: levels.sort((a,b) => a.level_order - b.level_order),
                        counts: calculateDefaultCounts(line.quantity, levels)
                    };
                } else if (hierarchies.length > 1) {
                    // Place in config without levels yet, trigger modal later
                    configs[line.id] = { hierarchies, needsSelection: true };
                } else {
                    configs[line.id] = { hierarchy: null, error: 'No hierarchy found' };
                }
            }
            setLineConfigs(configs);
        } catch (e) { console.error(e); }
        setLoading(false);
    };

    const calculateDefaultCounts = (qty, levels) => {
        const sorted = [...levels].sort((a,b) => b.level_order - a.level_order); 
        const counts = {};
        let remaining = qty;

        // Simple calculation: How many of each type to cover the quantity
        // Note: In real scenarios, this might be more complex (nesting logic)
        // Here we just provide standard counts per level for the operator to override
        levels.forEach(lvl => {
            const perLevel = lvl.contained_quantity || 1;
            counts[lvl.id] = Math.ceil(qty / perLevel);
        });
        return counts;
    };

    const handleHierarchySelection = async (line, hierarchy) => {
        setLoading(true);
        try {
            const levels = await PackagingAPI.getLevels(hierarchy.id);
            setLineConfigs(prev => ({
                ...prev,
                [line.id]: {
                    hierarchy,
                    levels: levels.sort((a,b) => a.level_order - b.level_order),
                    counts: calculateDefaultCounts(line.quantity, levels)
                }
            }));
            setHierarchyDialog({ open: false, line: null, options: [] });
        } catch (e) { console.error(e); }
        setLoading(false);
    };

    const updateLevelCount = (lineId, levelId, val) => {
        setLineConfigs(prev => ({
            ...prev,
            [lineId]: {
                ...prev[lineId],
                counts: { ...prev[lineId].counts, [levelId]: parseInt(val) || 0 }
            }
        }));
    };

    const handleDownloadPDF = () => {
        const doc = new jsPDF();
        doc.setFontSize(22);
        doc.text("SHIPPING LABELS", 105, 20, { align: 'center' });
        
        let y = 40;
        Object.entries(lineConfigs).forEach(([lineId, config]) => {
            const line = orderLines.find(l => l.id === lineId);
            
            config.levels?.forEach(lvl => {
                const count = config.counts[lvl.id] || 0;
                for (let i = 0; i < count; i++) {
                    if (y > 250) {
                        doc.addPage();
                        y = 20;
                    }
                    
                    doc.setDrawColor(0);
                    doc.rect(20, y, 170, 45); // Label border
                    
                    doc.setFontSize(12);
                    doc.setFont("helvetica", "bold");
                    doc.text(`${line?.material?.name || line?.material_code}`, 25, y + 10);
                    
                    doc.setFont("helvetica", "normal");
                    doc.setFontSize(9);
                    doc.text(`LEVEL: ${lvl.level_name}`, 25, y + 18);
                    doc.text(`ORDER: ${selectedOrder?.order_number}`, 25, y + 25);
                    doc.text(`SERIAL: ${lvl.level_code}-${Math.floor(Math.random()*10000)}`, 25, y + 32);
                    
                    // Design representation (simplified barcode for PDF)
                    doc.setDrawColor(100);
                    doc.rect(120, y + 10, 60, 25);
                    doc.setFontSize(7);
                    doc.text("BARCODE DATA", 150, y + 25, { align: 'center' });
                    
                    y += 55;
                }
            });
        });
        
        doc.save(`Shipping_Labels_${selectedOrder?.order_number}.pdf`);
    };

    const canProceedToSteps = () => {
        if (activeStep === 0) return !!selectedOrder;
        if (activeStep === 1) {
            return Object.values(lineConfigs).every(c => c.hierarchy && !c.needsSelection);
        }
        return true;
    };

    // --- Sub-components (Steps) ---

    const OrderGrid = () => (
        <Grid container spacing={3}>
            {orders.map(order => (
                <Grid item xs={12} md={4} key={order.id}>
                    <Card 
                        onClick={() => handleOrderSelect(order)}
                        sx={{ 
                            cursor: 'pointer',
                            transition: 'all 0.2s',
                            border: selectedOrder?.id === order.id ? '2px solid #3b82f6' : '1px solid #e2e8f0',
                            bgcolor: selectedOrder?.id === order.id ? '#eff6ff' : 'white',
                            '&:hover': { transform: 'translateY(-4px)', boxShadow: 3 }
                        }}
                    >
                        <CardContent>
                            <Box sx={{ display: 'flex', justifyContent: 'space-between', mb: 2 }}>
                                <Avatar sx={{ bgcolor: 'primary.main' }}><ShoppingCart /></Avatar>
                                <Chip label={order.status} size="small" color="warning" variant="outlined" />
                            </Box>
                            <Typography variant="h6" fontWeight="800">{order.order_number}</Typography>
                            <Box sx={{ display: 'flex', alignItems: 'center', gap: 1, mt: 1, color: 'text.secondary' }}>
                                <Business fontSize="small" />
                                <Typography variant="body2">{order.customer_name}</Typography>
                            </Box>
                            <Box sx={{ display: 'flex', alignItems: 'center', gap: 1, mt: 0.5, color: 'text.secondary' }}>
                                <CalendarMonth fontSize="small" />
                                <Typography variant="body2">{new Date(order.order_date).toLocaleDateString()}</Typography>
                            </Box>
                        </CardContent>
                    </Card>
                </Grid>
            ))}
            {orders.length === 0 && !loading && <Grid item xs={12}><Alert severity="info">No pending sales orders found.</Alert></Grid>}
        </Grid>
    );

    const PackagingConfig = () => (
        <Box>
            {orderLines.map(line => {
                const config = lineConfigs[line.id];
                return (
                    <Paper key={line.id} variant="outlined" sx={{ p: 3, mb: 3, borderRadius: 3 }}>
                        <Grid container spacing={3} alignItems="center">
                            <Grid item xs={12} md={4}>
                                <Typography variant="subtitle2" color="primary" fontWeight="bold">MATERIAL</Typography>
                                <Typography variant="h6" fontWeight="bold">{line.material?.name || `Material: ${line.material_code}`}</Typography>
                                <Typography variant="body2" color="text.secondary">Order Quantity: {line.quantity} {line.uom}</Typography>
                                
                                {config?.needsSelection && (
                                    <Button 
                                        sx={{ mt: 1 }} 
                                        variant="contained" 
                                        color="warning" 
                                        size="small"
                                        startIcon={<Edit />}
                                        onClick={() => setHierarchyDialog({ open: true, line, options: config.hierarchies })}
                                    >
                                        Choose Packaging Template
                                    </Button>
                                )}
                                {config?.hierarchy && !config.needsSelection && (
                                    <Box sx={{ mt: 1, p: 1, bgcolor: '#f0f9ff', borderRadius: 1, border: '1px solid #bae6fd', display: 'flex', alignItems: 'center', gap: 1 }}>
                                        <Storage fontSize="small" sx={{ color: '#0369a1' }} />
                                        <Typography variant="caption" fontWeight="800" sx={{ color: '#0369a1' }}>{config.hierarchy.name}</Typography>
                                        <IconButton size="small" onClick={() => setHierarchyDialog({ open: true, line, options: [config.hierarchy] })}><Edit sx={{ fontSize: 14 }} /></IconButton>
                                    </Box>
                                )}
                            </Grid>
                            
                            <Grid item xs={12} md={8}>
                                <Typography variant="subtitle2" color="text.secondary" sx={{ mb: 2, display: 'flex', alignItems: 'center', gap: 1 }}>
                                    <Calculate fontSize="small" /> Required Shipping Labels (Auto-Calculated)
                                </Typography>
                                <Grid container spacing={2}>
                                    {config?.levels?.map(lvl => (
                                        <Grid item xs={12} sm={4} key={lvl.id}>
                                            <Paper variant="outlined" sx={{ p: 2, bgcolor: '#f8fafc', borderRadius: 2 }}>
                                                <Typography variant="caption" fontWeight="bold" sx={{ display: 'block', mb: 1 }}>{lvl.level_name}</Typography>
                                                <TextField 
                                                    fullWidth 
                                                    type="number" 
                                                    size="small" 
                                                    value={config.counts[lvl.id] || 0}
                                                    onChange={(e) => updateLevelCount(line.id, lvl.id, e.target.value)}
                                                    InputProps={{ sx: { bgcolor: 'white' } }}
                                                />
                                                <Typography variant="caption" color="text.secondary" sx={{ mt: 0.5, display: 'block' }}>
                                                    {lvl.contained_quantity} units/pack
                                                </Typography>
                                            </Paper>
                                        </Grid>
                                    ))}
                                    {!config?.levels && <Typography variant="caption" color="error">Configure hierarchy to calculate labels.</Typography>}
                                </Grid>
                            </Grid>
                        </Grid>
                    </Paper>
                );
            })}
        </Box>
    );

    return (
        <Box sx={{ p: 3 }}>
            <Box className="no-print" sx={{ mb: 4, display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                <Box>
                    <Typography variant="h4" fontWeight="800" sx={{ letterSpacing: -0.5 }}>
                        Shipping Label Generator
                    </Typography>
                    <Typography variant="body2" color="text.secondary">
                        Fulfill Sales Orders with Automated Packaging & Label Calculations
                    </Typography>
                </Box>
                {selectedOrder && (
                    <Chip 
                        icon={<ShoppingCart />} 
                        label={`Order: ${selectedOrder.order_number}`} 
                        color="primary" 
                        variant="filled" 
                        sx={{ fontWeight: 'bold' }} 
                    />
                )}
            </Box>

            <Stepper activeStep={activeStep} sx={{ mb: 4 }} className="no-print">
                {steps.map((label) => (
                    <Step key={label}><StepLabel>{label}</StepLabel></Step>
                ))}
            </Stepper>

            {loading && <LinearProgress sx={{ mb: 3 }} />}

            <Box sx={{ minHeight: '50vh' }}>
                {activeStep === 0 && <OrderGrid />}
                {activeStep === 1 && <PackagingConfig />}
                {activeStep === 2 && (
                    <Box sx={{ py: 3 }}>
                        <Grid container spacing={4}>
                            <Grid item xs={12} md={6}>
                                <Paper variant="outlined" sx={{ p: 4, textAlign: 'center', height: '100%', borderRadius: 4, bgcolor: '#f8fafc' }}>
                                    <CheckCircle sx={{ fontSize: 64, color: 'success.main', mb: 2 }} />
                                    <Typography variant="h5" gutterBottom fontWeight="bold">Configuration Complete</Typography>
                                    <Typography variant="body2" color="text.secondary" sx={{ mb: 4 }}>
                                        Ready to generate labels for <b>{selectedOrder?.order_number}</b>. 
                                        Calculated <b>{Object.values(lineConfigs).reduce((acc, c) => acc + Object.values(c.counts || {}).reduce((a, b) => a + b, 0), 0)}</b> total labels across all packaging levels.
                                    </Typography>
                                    
                                    <Stack spacing={2} sx={{ maxWidth: 300, mx: 'auto' }}>
                                        <Button 
                                            variant="contained" 
                                            size="large" 
                                            startIcon={<Print />} 
                                            onClick={() => window.print()} 
                                            sx={{ py: 1.5, borderRadius: 3, fontWeight: 'bold' }}
                                        >
                                            Open Print Dialog
                                        </Button>
                                        <Button 
                                            variant="outlined" 
                                            size="large" 
                                            startIcon={<Storage />} 
                                            onClick={handleDownloadPDF}
                                            sx={{ py: 1.5, borderRadius: 3, fontWeight: 'bold' }}
                                        >
                                            Download PDF
                                        </Button>
                                    </Stack>
                                    
                                    <Button 
                                        sx={{ mt: 4 }}
                                        variant="text" 
                                        color="inherit"
                                        onClick={() => navigate('/label-management/material-inventory')}
                                    >
                                        Return to Inventory
                                    </Button>
                                </Paper>
                            </Grid>
                            <Grid item xs={12} md={6}>
                                <Typography variant="subtitle2" sx={{ mb: 1, fontWeight: 'bold' }} className="no-print">FINAL PREVIEW</Typography>
                                <Paper variant="outlined" sx={{ 
                                    overflow: 'hidden', 
                                    borderRadius: 4, 
                                    height: 450, 
                                    position: 'relative',
                                    '@media print': {
                                        height: 'auto',
                                        overflow: 'visible',
                                        border: 'none'
                                    }
                                }}>
                                    <Box className="no-print" sx={{ p: 2, bgcolor: 'grey.100', display: 'flex', gap: 1 }}>
                                        <Box sx={{ width: 10, height: 10, borderRadius: '50%', bgcolor: '#ff5f56' }} />
                                        <Box sx={{ width: 10, height: 10, borderRadius: '50%', bgcolor: '#ffbd2e' }} />
                                        <Box sx={{ width: 10, height: 10, borderRadius: '50%', bgcolor: '#27c93f' }} />
                                    </Box>
                                    <Box sx={{ p: 3, height: 'calc(100% - 40px)', overflow: 'auto', '@media print': { overflow: 'visible', p: 0 } }}>
                                        {Object.entries(lineConfigs).map(([lineId, config]) => (
                                            <Box key={lineId} sx={{ mb: 4, '@media print': { mb: 0 } }}>
                                                <Typography variant="overline" color="primary" className="no-print">{config.hierarchy?.name}</Typography>
                                                {config.levels?.map(lvl => (
                                                    <Box key={lvl.id} sx={{ 
                                                        mb: 2, 
                                                        transform: 'scale(0.8)', 
                                                        transformOrigin: 'top left',
                                                        '@media print': {
                                                            transform: 'none',
                                                            pageBreakAfter: 'always',
                                                            mb: 0,
                                                            display: 'flex',
                                                            justifyContent: 'center',
                                                            pt: 5
                                                        }
                                                    }}>
                                                       <Box className="no-print" sx={{ mb: 1 }}>
                                                            <Typography variant="caption" fontWeight="bold">{lvl.level_name}</Typography>
                                                       </Box>
                                                       {/* Render a small dummy label representation */}
                                                       <Paper sx={{ 
                                                            p: 2, 
                                                            border: '1px solid #000', 
                                                            width: 300, 
                                                            height: 180,
                                                            display: 'flex',
                                                            flexDirection: 'column',
                                                            justifyContent: 'space-between'
                                                        }}>
                                                            <Box>
                                                                <Typography variant="overline" sx={{ fontWeight: 'bold', fontSize: 10, borderBottom: '1px solid #eee' }}>ILMS SHIPPING LABEL</Typography>
                                                                <Typography variant="body2" sx={{ fontSize: 11, fontWeight: 'bold', mt: 1 }}>
                                                                    {orderLines.find(l => l.id === lineId)?.material?.name}
                                                                </Typography>
                                                                <Typography variant="caption" sx={{ fontSize: 9 }}>
                                                                    LVL: {lvl.level_name} | QTY: {lvl.contained_quantity}
                                                                </Typography>
                                                            </Box>
                                                            
                                                            <Box sx={{ display: 'flex', justifyContent: 'center' }}>
                                                                <Barcode 
                                                                    value={`${lvl.level_code}-00${Math.floor(Math.random()*9)}`} 
                                                                    width={1.2}
                                                                    height={40}
                                                                    fontSize={8}
                                                                />
                                                            </Box>
                                                            
                                                            <Box>
                                                                <Typography variant="caption" sx={{ fontSize: 8, color: 'text.secondary' }}>
                                                                    BATCH: 2024-X1 | SO: {selectedOrder?.order_number}
                                                                </Typography>
                                                            </Box>
                                                       </Paper>
                                                    </Box>
                                                ))}
                                            </Box>
                                        ))}
                                    </Box>
                                </Paper>
                            </Grid>
                        </Grid>
                    </Box>
                )}
            </Box>

            <Divider sx={{ my: 4 }} className="no-print" />
            <Box className="no-print" sx={{ display: 'flex', justifyContent: 'space-between' }}>
                <Button disabled={activeStep === 0} onClick={() => setActiveStep(s => s - 1)}>Back</Button>
                <Button 
                    variant="contained" 
                    disabled={!canProceedToSteps()} 
                    onClick={() => setActiveStep(s => s + 1)}
                    endIcon={<PlayCircleOutline />}
                >
                    {activeStep === steps.length - 1 ? 'Finish' : 'Next Step'}
                </Button>
            </Box>

            {/* Hierarchy Selection Dialog */}
            <Dialog open={hierarchyDialog.open} onClose={() => setHierarchyDialog(p => ({ ...p, open: false }))}>
                <DialogTitle>Select Packaging Hierarchy</DialogTitle>
                <DialogContent>
                    <Typography variant="body2" color="text.secondary" sx={{ mb: 2 }}>
                        Multiple hierarchy templates found for <b>{hierarchyDialog.line?.material_code}</b>. 
                        Please select the one for this shipment.
                    </Typography>
                    {hierarchyDialog.options.map(h => (
                        <Paper 
                            key={h.id} 
                            variant="outlined" 
                            sx={{ p: 2, mb: 1, cursor: 'pointer', '&:hover': { bgcolor: '#f8fafc' } }}
                            onClick={() => handleHierarchySelection(hierarchyDialog.line, h)}
                        >
                            <Typography variant="subtitle2" fontWeight="bold">{h.name}</Typography>
                        </Paper>
                    ))}
                </DialogContent>
                <DialogActions>
                    <Button onClick={() => setHierarchyDialog(p => ({ ...p, open: false }))}>Cancel</Button>
                </DialogActions>
            </Dialog>
        </Box>
    );
}
