// ilms-frontend/src/components/MaterialList.jsx
import React, { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Box, Button, Paper, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, Typography, IconButton, TextField, Chip, Dialog, DialogTitle, DialogContent } from '@mui/material';
import { Add, Edit, Delete, Search, Visibility } from '@mui/icons-material';
import { MaterialsAPI } from '../services/APIService';
import MaterialDetailCard from './MaterialDetailCard';

export default function MaterialList() {
  const navigate = useNavigate();
  const [materials, setMaterials] = useState([]);
  const [search, setSearch] = useState('');
  const [viewMaterial, setViewMaterial] = useState(null);

  useEffect(() => {
    load();
  }, []);

  const load = async () => {
    try {
      const data = await MaterialsAPI.list();
      setMaterials(data);
    } catch (e) { console.error(e); }
  };

  const handleDelete = async (code) => {
    if (window.confirm('Delete material?')) {
      await MaterialsAPI.remove(code);
      load();
    }
  };

  const filtered = materials.filter(m => m.name.toLowerCase().includes(search.toLowerCase()) || m.code.toLowerCase().includes(search.toLowerCase()));

  return (
    <Box>
      <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', mb: 3 }}>
        <Typography variant="h5" fontWeight="bold">Materials</Typography>
        <Button variant="contained" startIcon={<Add />} onClick={() => navigate('/materials/new')}>New Material</Button>
      </Box>

      <Paper sx={{ mb: 2, p: 2 }}>
        <Box sx={{ display: 'flex', alignItems: 'center' }}>
          <Search sx={{ color: 'text.secondary', mr: 1 }} />
          <TextField variant="standard" placeholder="Search by name or code..." fullWidth value={search} onChange={(e) => setSearch(e.target.value)} />
        </Box>
      </Paper>

      <TableContainer component={Paper} variant="outlined" sx={{ overflowX: 'auto' }}>
        <Table>
          <TableHead>
            <TableRow>
              <TableCell>SKU</TableCell>
              <TableCell>Type</TableCell>
              <TableCell>Group</TableCell>
              <TableCell>UOM</TableCell>
              <TableCell>Track & Trace</TableCell>
              <TableCell>Weight</TableCell>
              <TableCell align="right">Actions</TableCell>
            </TableRow>
          </TableHead>
          <TableBody>
            {filtered.map((row) => (
              <TableRow key={row.code}>
                <TableCell>
                  <Typography variant="body2" fontWeight="bold">{row.code}</Typography>
                  <Typography variant="caption" color="text.secondary">{row.name}</Typography>
                </TableCell>
                <TableCell><Chip label="FINISHED_GOODS" size="small" /></TableCell>
                <TableCell>{row.category ? row.category.replace(/_/g, ' ') : 'General'}</TableCell>
                <TableCell>{row.baseUom}</TableCell>
                <TableCell>
                  {row.isBatchManaged && <Chip label="Batch" size="small" color="primary" variant="outlined" sx={{ mr: 0.5 }} />}
                  {row.isSerialManaged && <Chip label="Serial" size="small" color="secondary" variant="outlined" />}
                </TableCell>
                <TableCell>{row.netWeight ? `${row.netWeight} ${row.weightUom || ''}` : '-'}</TableCell>
                <TableCell align="right">
                  <IconButton onClick={() => setViewMaterial(row)} color="info" title="Quick View"><Visibility /></IconButton>
                  <IconButton onClick={() => navigate(`/materials/${row.code}?mode=edit`)} color="primary" title="Edit Material"><Edit /></IconButton>
                  <IconButton onClick={() => handleDelete(row.code)} color="error" title="Delete"><Delete /></IconButton>
                </TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </TableContainer>

      {/* View Material Dialog */}
      <Dialog open={!!viewMaterial} onClose={() => setViewMaterial(null)} maxWidth="md" fullWidth PaperProps={{ sx: { borderRadius: 3 } }}>
        <DialogTitle sx={{ m: 0, p: 2, display: 'flex', justifyContent: 'space-between', alignItems: 'center', borderBottom: '1px solid #e2e8f0' }}>
          <Typography variant="h6" fontWeight="bold">Material Insight</Typography>
          <IconButton onClick={() => setViewMaterial(null)} sx={{ p: 1 }}>
             <Typography sx={{fontSize: 24, lineHeight: 1}}>×</Typography>
          </IconButton>
        </DialogTitle>
        <DialogContent sx={{ p: 0 }}>
          {viewMaterial && (
            <Box>
              <MaterialDetailCard 
                material={viewMaterial} 
                images={viewMaterial.images || []} 
              />
              <Box sx={{ p: 3, borderTop: '1px solid #e2e8f0', bgcolor: '#f8fafc', display: 'flex', justifyContent: 'center' }}>
                <Button 
                  variant="contained" 
                  color="primary"
                  onClick={() => {
                    navigate(`/materials/${viewMaterial.code}?mode=view`);
                    setViewMaterial(null);
                  }}
                  sx={{ borderRadius: 2, px: 4, textTransform: 'none', fontWeight: 'bold' }}
                >
                  View More Details
                </Button>
              </Box>
            </Box>
          )}
        </DialogContent>
      </Dialog>
    </Box>
  );
}

// ilms-frontend-angular/src/app/components/material-list/material-list.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router } from '@angular/router';
import { ApiService } from '../../services/api.service';
import { MatTableModule } from '@angular/material/table';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatInputModule } from '@angular/material/input';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatChipsModule } from '@angular/material/chips';
import { MatDialogModule, MatDialog } from '@angular/material/dialog';
import { FormsModule } from '@angular/forms';
import { MaterialDetailCardComponent } from '../material-detail-card/material-detail-card.component';

@Component({
  selector: 'app-material-list',
  standalone: true,
  imports: [
    CommonModule,
    MatTableModule,
    MatButtonModule,
    MatIconModule,
    MatInputModule,
    MatFormFieldModule,
    MatChipsModule,
    MatDialogModule,
    FormsModule,
    MaterialDetailCardComponent
  ],
  templateUrl: './material-list.component.html',
  styleUrl: './material-list.component.scss'
})
export class MaterialListComponent implements OnInit {
  materials: any[] = [];
  search = '';
  displayedColumns: string[] = ['sku', 'type', 'group', 'uom', 'trackTrace', 'weight', 'actions'];
  viewMaterial: any = null;

  constructor(
    private apiService: ApiService,
    private router: Router,
    private dialog: MatDialog
  ) {}

  ngOnInit() {
    this.loadMaterials();
  }

  async loadMaterials() {
    try {
      this.materials = await this.apiService.getMaterials();
    } catch (e) {
      console.error('Failed to load materials', e);
    }
  }

  get filteredMaterials() {
    return this.materials.filter(m => 
      m.name.toLowerCase().includes(this.search.toLowerCase()) || 
      m.code.toLowerCase().includes(this.search.toLowerCase())
    );
  }

  onDelete(code: string) {
    if (confirm('Are you sure you want to delete this material?')) {
      this.apiService.removeMaterial(code).then(() => {
        this.loadMaterials();
      });
    }
  }

  onView(material: any, template: any) {
    this.viewMaterial = material;
    this.dialog.open(template, {
      width: '800px',
      maxWidth: '90vw',
      panelClass: 'material-dialog'
    });
  }

  navigateToNew() {
    this.router.navigate(['/materials/new']);
  }

  navigateToEdit(code: string) {
    this.router.navigate(['/materials', code], { queryParams: { mode: 'edit' } });
  }

  navigateToDetails(code: string) {
    this.dialog.closeAll();
    this.router.navigate(['/materials', code], { queryParams: { mode: 'view' } });
  }
}

<div class="material-list-container">
  <div class="list-header">
    <h1 class="page-title">Materials</h1>
    <button mat-flat-button color="primary" (click)="navigateToNew()">
      <mat-icon>add</mat-icon> New Material
    </button>
  </div>

  <mat-card class="search-card">
    <mat-form-field appearance="standard" class="full-width">
      <mat-icon matPrefix>search</mat-icon>
      <input matInput [(ngModel)]="search" placeholder="Search by name or code...">
    </mat-form-field>
  </mat-card>

  <div class="table-wrapper mat-elevation-z1">
    <table mat-table [dataSource]="filteredMaterials" class="full-width">
      
      <!-- SKU Column -->
      <ng-container matColumnDef="sku">
        <th mat-header-cell *matHeaderCellDef> SKU </th>
        <td mat-cell *matCellDef="let row">
          <div class="sku-cell">
            <span class="code">{{row.code}}</span>
            <span class="name">{{row.name}}</span>
          </div>
        </td>
      </ng-container>

      <!-- Type Column -->
      <ng-container matColumnDef="type">
        <th mat-header-cell *matHeaderCellDef> Type </th>
        <td mat-cell *matCellDef="let row">
          <mat-chip-set>
            <mat-chip disableRipple class="type-chip">FINISHED_GOODS</mat-chip>
          </mat-chip-set>
        </td>
      </ng-container>

      <!-- Group Column -->
      <ng-container matColumnDef="group">
        <th mat-header-cell *matHeaderCellDef> Group </th>
        <td mat-cell *matCellDef="let row"> {{row.category?.replace('_', ' ') || 'General'}} </td>
      </ng-container>

      <!-- UOM Column -->
      <ng-container matColumnDef="uom">
        <th mat-header-cell *matHeaderCellDef> UOM </th>
        <td mat-cell *matCellDef="let row"> {{row.baseUom}} </td>
      </ng-container>

      <!-- Track & Trace Column -->
      <ng-container matColumnDef="trackTrace">
        <th mat-header-cell *matHeaderCellDef> Track & Trace </th>
        <td mat-cell *matCellDef="let row">
          <mat-chip-set>
            <mat-chip *ngIf="row.isBatchManaged" color="primary" class="mini-chip">Batch</mat-chip>
            <mat-chip *ngIf="row.isSerialManaged" color="accent" class="mini-chip">Serial</mat-chip>
          </mat-chip-set>
        </td>
      </ng-container>

      <!-- Weight Column -->
      <ng-container matColumnDef="weight">
        <th mat-header-cell *matHeaderCellDef> Weight </th>
        <td mat-cell *matCellDef="let row"> {{row.netWeight ? row.netWeight + ' ' + (row.weightUom || '') : '-'}} </td>
      </ng-container>

      <!-- Actions Column -->
      <ng-container matColumnDef="actions">
        <th mat-header-cell *matHeaderCellDef class="text-right"> Actions </th>
        <td mat-cell *matCellDef="let row" class="text-right">
          <button mat-icon-button color="info" (click)="onView(row, viewDialog)" title="Quick View">
            <mat-icon>visibility</mat-icon>
          </button>
          <button mat-icon-button color="primary" (click)="navigateToEdit(row.code)" title="Edit Material">
            <mat-icon>edit</mat-icon>
          </button>
          <button mat-icon-button color="warn" (click)="onDelete(row.code)" title="Delete">
            <mat-icon>delete</mat-icon>
          </button>
        </td>
      </ng-container>

      <tr mat-header-row *matHeaderRowDef="displayedColumns"></tr>
      <tr mat-row *matRowDef="let row; columns: displayedColumns;"></tr>
    </table>
  </div>
</div>

<!-- View Material Dialog Template -->
<ng-template #viewDialog>
  <div class="dialog-header">
    <h2 mat-dialog-title>Material Insight</h2>
    <button mat-icon-button (click)="dialog.closeAll()">
      <mat-icon>close</mat-icon>
    </button>
  </div>
  <mat-dialog-content class="no-padding">
    <app-material-detail-card [material]="viewMaterial" [images]="viewMaterial?.images || []"></app-material-detail-card>
  </mat-dialog-content>
  <mat-dialog-actions align="center" class="dialog-footer">
    <button mat-flat-button color="primary" (click)="navigateToDetails(viewMaterial.code)" class="view-more-btn">
      View More Details
    </button>
  </mat-dialog-actions>
</ng-template>
