// ilms-frontend-angular/src/app/features/materials/components/material-create/material-create.component.ts
import { Component, OnInit, ViewChild, ElementRef } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormBuilder, FormGroup, FormArray, Validators, ReactiveFormsModule, FormsModule } from '@angular/forms';
import { Router, ActivatedRoute } from '@angular/router';
import { MatStepperModule } from '@angular/material/stepper';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatSelectModule } from '@angular/material/select';
import { MatButtonModule } from '@angular/material/button';
import { MatCheckboxModule } from '@angular/material/checkbox';
import { MatIconModule } from '@angular/material/icon';
import { MatCardModule } from '@angular/material/card';
import { MatChipsModule } from '@angular/material/chips';
import { MatAutocompleteModule } from '@angular/material/autocomplete';
import { MatDialogModule, MatDialog } from '@angular/material/dialog';
import { MatSnackBarModule, MatSnackBar } from '@angular/material/snack-bar';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import { MaterialService } from '../../services/material.service';
import { MaterialDetailCardComponent } from '../../../../shared/components/material-detail-card/material-detail-card.component';

@Component({
  selector: 'app-material-create',
  standalone: true,
  imports: [
    CommonModule,
    ReactiveFormsModule,
    FormsModule,
    MatStepperModule,
    MatFormFieldModule,
    MatInputModule,
    MatSelectModule,
    MatButtonModule,
    MatCheckboxModule,
    MatIconModule,
    MatCardModule,
    MatChipsModule,
    MatAutocompleteModule,
    MatDialogModule,
    MatSnackBarModule,
    MatProgressSpinnerModule,
    MaterialDetailCardComponent
  ],
  templateUrl: './material-create.component.html',
  styleUrl: './material-create.component.scss'
})
export class MaterialCreateComponent implements OnInit {
  @ViewChild('fileInput') fileInput!: ElementRef;
  
  generalForm!: FormGroup;
  dimensionsForm!: FormGroup;
  storageForm!: FormGroup;
  packagingForm!: FormGroup;
  identifiersForm!: FormGroup;
  flagsForm!: FormGroup;
  
  images: any[] = [];
  saving = false;
  loading = false;
  code: string | null = null;
  mode: 'create' | 'edit' | 'view' = 'create';

  TYPES = ['Finished Goods', 'Raw Material', 'Packaging Material'];
  STATES = ['Liquid', 'Solid', 'Gel', 'Powder'];
  CLASSES = ['Bottles', 'Tubes', 'Jars', 'Cartons'];
  GROUPS = ['Shampoo', 'Fairness Cream', 'Body Wash', 'Hand Sanitizer'];
  STORAGE_TYPES = ['Ambient', 'Cool Storage', 'Cold Storage'];
  PROCUREMENT_TYPES = ['Make To Stock', 'Make To Order', 'Purchase'];
  VEHICLE_TYPES = ['Bulker', 'Tanker', 'Flatbed', 'Refrigerated Truck', 'Standard Container'];
  UOMS = ['EA', 'KG', 'LT', 'TON', 'ML', 'GM'];
  PACKAGING_MATERIAL_OPTIONS = ['Box', 'Carton', 'Wooden Crate', 'Premium Wrap', 'Shrink Wrap'];
  SKU_TYPE_OPTIONS = ['Bottle', 'Tube', 'Jar', 'Sachet', 'Box', 'Carton', 'Other'];

  constructor(
    private fb: FormBuilder,
    private materialService: MaterialService,
    public router: Router,
    public route: ActivatedRoute,
    private snackBar: MatSnackBar,
    public dialog: MatDialog
  ) {}

  ngOnInit() {
    this.initForms();
    this.route.params.subscribe(params => {
      this.code = params['code'];
      if (this.code) {
        this.mode = (this.route.snapshot.queryParams['mode'] as any) || 'edit';
        this.loadMaterial(this.code);
      } else {
        this.mode = 'create';
      }
    });
  }

  async loadMaterial(code: string) {
    this.loading = true;
    try {
      const data = await this.materialService.getMaterial(code);
      this.patchForms(data);
    } catch (e) {
      console.error('Failed to load material', e);
      this.snackBar.open('Failed to load material details', 'Close', { duration: 3000 });
    } finally {
      this.loading = false;
    }
  }

  patchForms(data: any) {
    this.generalForm.patchValue({
      materialCode: data.code,
      materialName: data.name,
      description: data.description,
      type: data.type,
      materialClass: data.class,
      materialGroup: data.category,
      materialState: data.state,
      countryOfOrigin: data.countryOfOrigin
    });

    this.dimensionsForm.patchValue({
      baseUOM: data.baseUom,
      netWeightKg: data.netWeight,
      netWeightUom: data.weightUom,
      lengthMM: data.length,
      widthMM: data.width,
      heightMM: data.height,
      dimensionUom: data.dimensionUom
    });

    this.flagsForm.patchValue({
      isBatchManaged: !!data.isBatchManaged,
      isSerialized: !!data.isSerialManaged
    });

    if (data.images) {
      this.images = data.images.map((img: any) => ({
        name: img.filename || 'Image',
        dataUrl: img.url,
        isPrimary: img.type === 'MAIN'
      }));
    }
  }

  initForms() {
    this.generalForm = this.fb.group({
      materialCode: ['', Validators.required],
      materialName: ['', Validators.required],
      description: [''],
      countryOfOrigin: [''],
      type: ['', Validators.required],
      materialClass: ['', Validators.required],
      materialGroup: ['', Validators.required],
      materialState: ['']
    });

    this.dimensionsForm = this.fb.group({
      baseUOM: ['', Validators.required],
      netWeightKg: [''],
      netWeightUom: ['KG'],
      lengthMM: [''],
      widthMM: [''],
      heightMM: [''],
      dimensionUom: ['MM'],
      tradeUOM: [''],
      tradeWeightKg: [''],
      tradeWeightUom: ['KG'],
      tradeLengthMM: [''],
      tradeWidthMM: [''],
      tradeHeightMM: [''],
      tradeDimensionUom: ['MM']
    });

    this.storageForm = this.fb.group({
      shelfLifeDays: [''],
      storageType: [''],
      procurementType: [''],
      vehicleType: [''],
      temperatureMin: [''],
      temperatureMax: [''],
      humidityMin: [''],
      humidityMax: [''],
      hazardousClass: [''],
      epcFormat: [''],
      envParameters: [''],
      precautions: ['']
    });

    this.packagingForm = this.fb.group({
      packagingTypes: [[]],
      skus: this.fb.array([])
    });

    this.identifiersForm = this.fb.group({
      materialEANupc: [''],
      upc: [''],
      externalERPCode: [''],
      packagingMaterialCode: ['']
    });

    this.flagsForm = this.fb.group({
      isPackaged: [false],
      isFragile: [false],
      isHighValue: [false],
      isEnvSensitive: [false],
      isBatchManaged: [false],
      isSerialized: [false]
    });
  }

  get skus() {
    return this.packagingForm.get('skus') as FormArray;
  }

  addSku() {
    const sku = this.fb.group({
      name: [''],
      type: [''],
      packagingMaterial: [''],
      quantity: [1],
      length: [''],
      width: [''],
      height: [''],
      dimUom: ['MM'],
      weight: [''],
      weightUom: ['KG']
    });
    this.skus.push(sku);
  }

  removeSku(index: number) {
    this.skus.removeAt(index);
  }

  handleImageUpload(event: any) {
    if (this.mode === 'view') return;
    const files = Array.from(event.target.files) as File[];
    files.forEach(file => {
      if (!file.type.startsWith('image/')) return;
      const reader = new FileReader();
      reader.onload = (evt: any) => {
        this.images.push({
          name: file.name,
          dataUrl: evt.target.result,
          isPrimary: this.images.length === 0
        });
      };
      reader.readAsDataURL(file);
    });
    event.target.value = '';
  }

  removeImage(index: number) {
    if (this.mode === 'view') return;
    const isPrimary = this.images[index].isPrimary;
    this.images.splice(index, 1);
    if (isPrimary && this.images.length > 0) {
      this.images[0].isPrimary = true;
    }
  }

  setPrimaryImage(index: number) {
    if (this.mode === 'view') return;
    this.images.forEach((img, i) => img.isPrimary = i === index);
  }

  handleAutoFill() {
    const unique = Math.floor(Math.random() * 1000);
    this.generalForm.patchValue({
      materialCode: `MAT-${unique}`,
      materialName: `Auto Material ${unique}`,
      description: 'Auto-generated material for testing',
      countryOfOrigin: 'India',
      type: this.TYPES[0],
      materialClass: this.CLASSES[0],
      materialGroup: this.GROUPS[0],
      materialState: this.STATES[0]
    });

    this.dimensionsForm.patchValue({
      baseUOM: 'EA',
      netWeightKg: 0.5,
      netWeightUom: 'KG',
      lengthMM: 50,
      widthMM: 50,
      heightMM: 150,
      dimensionUom: 'MM'
    });

    this.flagsForm.patchValue({
      isBatchManaged: true,
      isPackaged: true
    });
  }

  get fullFormValue() {
    return {
      ...this.generalForm.value,
      ...this.dimensionsForm.value,
      ...this.storageForm.value,
      ...this.packagingForm.value,
      ...this.identifiersForm.value,
      ...this.flagsForm.value,
      images: this.images.map(img => img.dataUrl)
    };
  }

  async submit() {
    if (this.generalForm.invalid) {
      this.snackBar.open('Please complete the general section.', 'Close', { duration: 3000 });
      return;
    }

    this.saving = true;
    try {
      const formVal = this.fullFormValue;
      const payload = {
        code: formVal.materialCode,
        name: formVal.materialName,
        description: formVal.description,
        type: formVal.type,
        category: formVal.materialGroup,
        baseUom: formVal.baseUOM,
        isBatchManaged: formVal.isBatchManaged,
        isSerialManaged: formVal.isSerialized,
        shelfLifeDays: formVal.shelfLifeDays ? Number(formVal.shelfLifeDays) : null,
        grossWeight: formVal.tradeWeightKg ? Number(formVal.tradeWeightKg) : null,
        netWeight: formVal.netWeightKg ? Number(formVal.netWeightKg) : null,
        weightUom: formVal.netWeightUom || 'KG',
        length: formVal.lengthMM ? Number(formVal.lengthMM) : null,
        width: formVal.widthMM ? Number(formVal.widthMM) : null,
        height: formVal.heightMM ? Number(formVal.heightMM) : null,
        dimensionUom: formVal.dimensionUom || 'MM',
        status: 'ACTIVE'
      };

      if (this.mode === 'create') {
        await this.materialService.createMaterial(payload);
        this.snackBar.open('Material created successfully!', 'Close', { duration: 3000 });
      } else {
        await this.materialService.updateMaterial(this.code!, payload);
        this.snackBar.open('Material updated successfully!', 'Close', { duration: 3000 });
      }
      this.router.navigate(['/materials']);
    } catch (e: any) {
      console.error(e);
      this.snackBar.open(e.message || 'Failed to process material', 'Close', { duration: 5000 });
    } finally {
      this.saving = false;
    }
  }

  openPreview(template: any) {
    this.dialog.open(template, {
      width: '1000px',
      maxWidth: '95vw'
    });
  }

  switchMode(newMode: 'edit' | 'view') {
    this.mode = newMode;
  }
}

<div *ngIf="loading" class="loading-overlay">
  <mat-spinner></mat-spinner>
</div>

<mat-card class="create-material-card" *ngIf="!loading">
  <div class="card-header">
    <div class="header-left">
      <button mat-icon-button (click)="router.navigate(['/materials'])"><mat-icon>arrow_back</mat-icon></button>
      <h2 class="title">
        {{ mode === 'create' ? 'Create Material' : (mode === 'view' ? 'Material Insight' : 'Refine Material') }}
      </h2>
      <mat-chip *ngIf="code" class="code-chip">{{code}}</mat-chip>
    </div>
    <div class="header-right">
      <button mat-button color="accent" (click)="handleAutoFill()" *ngIf="mode === 'create'">
        <mat-icon>auto_fix_high</mat-icon> Auto-Fill
      </button>
      <button mat-flat-button color="primary" (click)="switchMode('edit')" *ngIf="mode === 'view'">
        <mat-icon>edit</mat-icon> Switch to Edit
      </button>
    </div>
  </div>

  <mat-stepper #stepper="matHorizontalStepper" [linear]="true" class="material-stepper">
    <!-- Step 0: General -->
    <mat-step [stepControl]="generalForm">
      <ng-template matStepLabel>General</ng-template>
      <form [formGroup]="generalForm" class="step-content">
        <h3 class="section-title">General Information</h3>
        <div class="form-grid">
          <mat-form-field appearance="outline">
            <mat-label>Material Code</mat-label>
            <input matInput formControlName="materialCode" [readonly]="mode !== 'create'" required>
          </mat-form-field>
          <mat-form-field appearance="outline">
            <mat-label>Material Name</mat-label>
            <input matInput formControlName="materialName" [readonly]="mode === 'view'" required>
          </mat-form-field>
          <mat-form-field appearance="outline" class="full-width">
            <mat-label>Description</mat-label>
            <textarea matInput formControlName="description" [readonly]="mode === 'view'" rows="2"></textarea>
          </mat-form-field>
          <mat-form-field appearance="outline">
            <mat-label>Country of Origin</mat-label>
            <input matInput formControlName="countryOfOrigin" [readonly]="mode === 'view'">
          </mat-form-field>
          <mat-form-field appearance="outline">
            <mat-label>Material Type</mat-label>
            <mat-select formControlName="type" [disabled]="mode === 'view'" required>
              <mat-option *ngFor="let t of TYPES" [value]="t">{{t}}</mat-option>
            </mat-select>
          </mat-form-field>
          <mat-form-field appearance="outline">
            <mat-label>Material State</mat-label>
            <mat-select formControlName="materialState" [disabled]="mode === 'view'">
              <mat-option *ngFor="let t of STATES" [value]="t">{{t}}</mat-option>
            </mat-select>
          </mat-form-field>
          <mat-form-field appearance="outline">
            <mat-label>Material Class</mat-label>
            <mat-select formControlName="materialClass" [disabled]="mode === 'view'" required>
              <mat-option *ngFor="let t of CLASSES" [value]="t">{{t}}</mat-option>
            </mat-select>
          </mat-form-field>
          <mat-form-field appearance="outline">
            <mat-label>Material Group</mat-label>
            <mat-select formControlName="materialGroup" [disabled]="mode === 'view'" required>
              <mat-option *ngFor="let t of GROUPS" [value]="t">{{t}}</mat-option>
            </mat-select>
          </mat-form-field>
        </div>
        <div class="stepper-actions">
          <button mat-button matStepperNext>Next</button>
        </div>
      </form>
    </mat-step>

    <!-- Step 1: Dimensions & Weight -->
    <mat-step [stepControl]="dimensionsForm">
      <ng-template matStepLabel>Dimensions</ng-template>
      <form [formGroup]="dimensionsForm" class="step-content">
        <h3 class="section-title">Dimensions & Weight</h3>
        <div class="form-grid">
          <div class="grid-sub-heading full-width">Base Specification</div>
          <mat-form-field appearance="outline">
            <mat-label>Base UOM</mat-label>
            <mat-select formControlName="baseUOM" [disabled]="mode === 'view'" required>
              <mat-option *ngFor="let t of UOMS" [value]="t">{{t}}</mat-option>
            </mat-select>
          </mat-form-field>
          <mat-form-field appearance="outline">
            <mat-label>Net Weight</mat-label>
            <input matInput type="number" formControlName="netWeightKg" [readonly]="mode === 'view'">
          </mat-form-field>
          <mat-form-field appearance="outline">
            <mat-label>Weight UOM</mat-label>
            <mat-select formControlName="netWeightUom" [disabled]="mode === 'view'">
              <mat-option *ngFor="let t of UOMS" [value]="t">{{t}}</mat-option>
            </mat-select>
          </mat-form-field>
          <div class="full-width"></div>
          <mat-form-field appearance="outline">
            <mat-label>Length (MM)</mat-label>
            <input matInput type="number" formControlName="lengthMM" [readonly]="mode === 'view'">
          </mat-form-field>
          <mat-form-field appearance="outline">
            <mat-label>Width (MM)</mat-label>
            <input matInput type="number" formControlName="widthMM" [readonly]="mode === 'view'">
          </mat-form-field>
          <mat-form-field appearance="outline">
            <mat-label>Height (MM)</mat-label>
            <input matInput type="number" formControlName="heightMM" [readonly]="mode === 'view'">
          </mat-form-field>
          <mat-form-field appearance="outline">
            <mat-label>Dim UOM</mat-label>
            <mat-select formControlName="dimensionUom" [disabled]="mode === 'view'">
              <mat-option value="MM">MM</mat-option>
              <mat-option value="CM">CM</mat-option>
              <mat-option value="IN">IN</mat-option>
              <mat-option value="M">M</mat-option>
            </mat-select>
          </mat-form-field>
        </div>
        <div class="stepper-actions">
          <button mat-button matStepperPrevious>Back</button>
          <button mat-button matStepperNext>Next</button>
        </div>
      </form>
    </mat-step>

    <!-- Step 2: Storage & Handling -->
    <mat-step [stepControl]="storageForm">
      <ng-template matStepLabel>Storage</ng-template>
      <form [formGroup]="storageForm" class="step-content">
        <h3 class="section-title">Storage & Handling</h3>
        <div class="form-grid">
          <mat-form-field appearance="outline">
            <mat-label>Shelf Life (days)</mat-label>
            <input matInput type="number" formControlName="shelfLifeDays" [readonly]="mode === 'view'">
          </mat-form-field>
          <mat-form-field appearance="outline">
            <mat-label>Storage Type</mat-label>
            <mat-select formControlName="storageType" [disabled]="mode === 'view'">
              <mat-option *ngFor="let t of STORAGE_TYPES" [value]="t">{{t}}</mat-option>
            </mat-select>
          </mat-form-field>
          <mat-form-field appearance="outline">
            <mat-label>Procurement Type</mat-label>
            <mat-select formControlName="procurementType" [disabled]="mode === 'view'">
              <mat-option *ngFor="let t of PROCUREMENT_TYPES" [value]="t">{{t}}</mat-option>
            </mat-select>
          </mat-form-field>
          <mat-form-field appearance="outline">
            <mat-label>Vehicle Type</mat-label>
            <mat-select formControlName="vehicleType" [disabled]="mode === 'view'">
              <mat-option *ngFor="let t of VEHICLE_TYPES" [value]="t">{{t}}</mat-option>
            </mat-select>
          </mat-form-field>
          <mat-form-field appearance="outline">
            <mat-label>Temp Min (°C)</mat-label>
            <input matInput type="number" formControlName="temperatureMin" [readonly]="mode === 'view'">
          </mat-form-field>
          <mat-form-field appearance="outline">
            <mat-label>Temp Max (°C)</mat-label>
            <input matInput type="number" formControlName="temperatureMax" [readonly]="mode === 'view'">
          </mat-form-field>
        </div>
        <div class="stepper-actions">
          <button mat-button matStepperPrevious>Back</button>
          <button mat-button matStepperNext>Next</button>
        </div>
      </form>
    </mat-step>

    <!-- Step 3: Packaging -->
    <mat-step [stepControl]="packagingForm">
      <ng-template matStepLabel>Packaging</ng-template>
      <form [formGroup]="packagingForm" class="step-content">
        <h3 class="section-title">Packaging Settings</h3>
        <div class="form-grid">
          <mat-form-field appearance="outline" class="full-width">
            <mat-label>Packaging Types</mat-label>
            <mat-chip-grid #chipGrid [disabled]="mode === 'view'">
                <mat-chip-row *ngFor="let type of packagingForm.get('packagingTypes')?.value" (removed)="packagingForm.get('packagingTypes')?.value.indexOf(type)">
                    {{type}}
                    <button matChipRemove *ngIf="mode !== 'view'"><mat-icon>cancel</mat-icon></button>
                </mat-chip-row>
                <input placeholder="New type..." [matChipInputFor]="chipGrid" [disabled]="mode === 'view'">
            </mat-chip-grid>
          </mat-form-field>

          <div class="sku-header full-width">
            <span>SKU & Packaging Configurations</span>
            <button mat-button color="primary" type="button" (click)="addSku()" *ngIf="mode !== 'view'">
              <mat-icon>add</mat-icon> Add Configuration
            </button>
          </div>

          <div formArrayName="skus" class="full-width">
            <div *ngFor="let sku of skus.controls; let i=index" [formGroupName]="i" class="sku-card mui-card">
              <div class="sku-card-header">
                <span>Configuration {{i+1}}</span>
                <button mat-icon-button color="warn" (click)="removeSku(i)" *ngIf="mode !== 'view'">
                  <mat-icon>delete</mat-icon>
                </button>
              </div>
              <div class="form-grid">
                <mat-form-field appearance="outline">
                  <mat-label>SKU Name</mat-label>
                  <input matInput formControlName="name" [readonly]="mode === 'view'">
                </mat-form-field>
                <mat-form-field appearance="outline">
                  <mat-label>SKU Type</mat-label>
                  <mat-select formControlName="type" [disabled]="mode === 'view'">
                    <mat-option *ngFor="let t of SKU_TYPE_OPTIONS" [value]="t">{{t}}</mat-option>
                  </mat-select>
                </mat-form-field>
                <mat-form-field appearance="outline">
                  <mat-label>Packaging Material</mat-label>
                  <mat-select formControlName="packagingMaterial" [disabled]="mode === 'view'">
                    <mat-option *ngFor="let t of PACKAGING_MATERIAL_OPTIONS" [value]="t">{{t}}</mat-option>
                  </mat-select>
                </mat-form-field>
                <mat-form-field appearance="outline" style="width: 100px;">
                  <mat-label>Qty</mat-label>
                  <input matInput type="number" formControlName="quantity" [readonly]="mode === 'view'">
                </mat-form-field>
              </div>
            </div>
          </div>
        </div>
        <div class="stepper-actions">
          <button mat-button matStepperPrevious>Back</button>
          <button mat-button matStepperNext>Next</button>
        </div>
      </form>
    </mat-step>

    <!-- Step 4: Identifiers -->
    <mat-step [stepControl]="identifiersForm">
      <ng-template matStepLabel>Identifiers</ng-template>
      <form [formGroup]="identifiersForm" class="step-content">
        <h3 class="section-title">Identifiers</h3>
        <div class="form-grid">
          <mat-form-field appearance="outline">
            <mat-label>Material EAN/UPC</mat-label>
            <input matInput formControlName="materialEANupc" [readonly]="mode === 'view'">
          </mat-form-field>
          <mat-form-field appearance="outline">
            <mat-label>UPC</mat-label>
            <input matInput formControlName="upc" [readonly]="mode === 'view'">
          </mat-form-field>
          <mat-form-field appearance="outline">
            <mat-label>External ERP Code</mat-label>
            <input matInput formControlName="externalERPCode" [readonly]="mode === 'view'">
          </mat-form-field>
        </div>
        <div class="stepper-actions">
          <button mat-button matStepperPrevious>Back</button>
          <button mat-button matStepperNext>Next</button>
        </div>
      </form>
    </mat-step>

    <!-- Step 5: Images -->
    <mat-step>
      <ng-template matStepLabel>Images</ng-template>
      <div class="step-content">
        <h3 class="section-title"><mat-icon>image</mat-icon> Product Images</h3>
        <p class="section-subtitle" *ngIf="mode !== 'view'">Upload images of the material. The first image will be set as the primary image.</p>
        
        <input type="file" #fileInput hidden accept="image/*" multiple (change)="handleImageUpload($event)">
        <button mat-stroked-button color="primary" (click)="fileInput.click()" style="margin-bottom: 24px;" *ngIf="mode !== 'view'">
          <mat-icon>cloud_upload</mat-icon> Upload Images
        </button>

        <div class="images-grid" *ngIf="images.length > 0; else noImages">
          <mat-card *ngFor="let img of images; let i=index" class="image-card">
            <div *ngIf="img.isPrimary" class="primary-tag">PRIMARY</div>
            <img mat-card-image [src]="img.dataUrl" [alt]="img.name">
            <mat-card-actions align="end" *ngIf="mode !== 'view'">
              <button mat-icon-button (click)="setPrimaryImage(i)" [disabled]="img.isPrimary" matTooltip="Set as primary">
                <mat-icon [color]="img.isPrimary ? 'primary' : ''">image</mat-icon>
              </button>
              <button mat-icon-button color="warn" (click)="removeImage(i)" matTooltip="Remove">
                <mat-icon>delete</mat-icon>
              </button>
            </mat-card-actions>
          </mat-card>
        </div>
        <ng-template #noImages>
          <div class="info-alert">No images available.</div>
        </ng-template>

        <div class="stepper-actions">
          <button mat-button matStepperPrevious>Back</button>
          <button mat-button matStepperNext>Next</button>
        </div>
      </div>
    </mat-step>

    <!-- Step 6: Flags -->
    <mat-step [stepControl]="flagsForm">
      <ng-template matStepLabel>Flags</ng-template>
      <form [formGroup]="flagsForm" class="step-content">
        <h3 class="section-title">Status & Special Flags</h3>
        <div class="flags-grid">
          <mat-checkbox formControlName="isPackaged" [disabled]="mode === 'view'">Packaged Material</mat-checkbox>
          <mat-checkbox formControlName="isFragile" [disabled]="mode === 'view'">Fragile Material</mat-checkbox>
          <mat-checkbox formControlName="isHighValue" [disabled]="mode === 'view'">High Value</mat-checkbox>
          <mat-checkbox formControlName="isEnvSensitive" [disabled]="mode === 'view'">Environment Sensitive</mat-checkbox>
          <mat-checkbox formControlName="isBatchManaged" [disabled]="mode === 'view'">Batch Material</mat-checkbox>
          <mat-checkbox formControlName="isSerialized" [disabled]="mode === 'view'">Serialized</mat-checkbox>
        </div>
        <div class="stepper-actions">
          <button mat-button matStepperPrevious>Back</button>
          <button mat-button matStepperNext>Next</button>
        </div>
      </form>
    </mat-step>

    <!-- Step 7: Review & Submit -->
    <mat-step>
      <ng-template matStepLabel>Review</ng-template>
      <div class="step-content">
        <h3 class="section-title">Review & Submit</h3>
        <app-material-detail-card [material]="fullFormValue" [images]="images"></app-material-detail-card>
        
        <div class="stepper-actions">
          <button mat-button matStepperPrevious>Back</button>
          <div class="final-actions">
            <button mat-button (click)="openPreview(previewTpl)">Preview</button>
            <button mat-flat-button color="primary" (click)="submit()" [disabled]="saving" *ngIf="mode !== 'view'">
              {{ saving ? 'Saving...' : (mode === 'create' ? 'Submit' : 'Update') }}
            </button>
          </div>
        </div>
      </div>
    </mat-step>
  </mat-stepper>
</mat-card>

<!-- Preview Dialog Template -->
<ng-template #previewTpl>
  <h2 mat-dialog-title>Preview Material</h2>
  <mat-dialog-content>
    <app-material-detail-card [material]="fullFormValue" [images]="images"></app-material-detail-card>
  </mat-dialog-content>
  <mat-dialog-actions align="end">
    <button mat-button mat-dialog-close>Close</button>
  </mat-dialog-actions>
</ng-template>

// ilms-frontend/src/components/MaterialCreate.jsx
import React, { useMemo, useState, useRef } from 'react';
import {
  Box,
  Paper,
  Typography,
  Grid,
  TextField,
  Checkbox,
  FormControlLabel,
  MenuItem,
  Button,
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  Snackbar,
  Alert,
  Stepper,
  Step,
  StepLabel,
  IconButton,
  Card,
  CardMedia,
  CardActions,
  Tooltip,
  Autocomplete, Chip,
} from '@mui/material';
import { AutoFixHigh, CloudUpload, Delete, Image as ImageIcon, Add } from '@mui/icons-material';
import { useNavigate } from 'react-router-dom';
import { MaterialsAPI } from '../services/APIService';
import MaterialDetailCard from './MaterialDetailCard';

const TYPES = ['Finished Goods', 'Raw Material', 'Packaging Material'];
const STATES = ['Liquid', 'Solid', 'Gel', 'Powder'];
const CLASSES = ['Bottles', 'Tubes', 'Jars', 'Cartons'];
const GROUPS = ['Shampoo', 'Fairness Cream', 'Body Wash', 'Hand Sanitizer'];
const STORAGE_TYPES = ['Ambient', 'Cool Storage', 'Cold Storage'];
const PROCUREMENT_TYPES = ['Make To Stock', 'Make To Order', 'Purchase'];
const VEHICLE_TYPES = ['Bulker', 'Tanker', 'Flatbed', 'Refrigerated Truck', 'Standard Container'];
const UOMS = ['EA', 'KG', 'LT', 'TON', 'ML', 'GM'];
const STEPS = ['General', 'Dimensions & Weight', 'Storage & Handling', 'Packaging', 'Identifiers', 'Images', 'Flags', 'Review & Submit'];

export default function MaterialCreate() {
  const navigate = useNavigate();
  const fileInputRef = useRef(null);
  const [activeStep, setActiveStep] = useState(0);
  const [images, setImages] = useState([]); // Array of { name, dataUrl, isPrimary }
  const [form, setForm] = useState({
    materialCode: '',
    materialName: '',
    description: '',
    packagingTypes: [],
    packagingMaterials: [],
    skus: [],
    countryOfOrigin: '',
    type: '',
    materialClass: '',
    materialGroup: '',
    materialState: '',
    baseUOM: '',
    netWeightKg: '',
    netWeightUom: 'KG',
    lengthMM: '',
    widthMM: '',
    heightMM: '',
    dimensionUom: 'MM',
    shelfLifeDays: '',
    materialEANupc: '',
    upc: '',
    storageType: '',
    procurementType: '',
    vehicleType: '',
    tradeUOM: '',
    tradeWeightKg: '',
    tradeWeightUom: 'KG',
    tradeLengthMM: '',
    tradeWidthMM: '',
    tradeHeightMM: '',
    tradeDimensionUom: 'MM',
    isPackaged: false,
    isFragile: false,
    isHighValue: false,
    isEnvSensitive: false,
    isBatchManaged: false,
    isSerialized: false,
    handlingParameter: {
      temperatureMin: '',
      temperatureMax: '',
      humidityMin: '',
      humidityMax: '',
      hazardousClass: '',
      epcFormat: '',
      envParameters: '',
      precautions: '',
    },
  });
  const [previewOpen, setPreviewOpen] = useState(false);
  const [saving, setSaving] = useState(false);
  const [toast, setToast] = useState({ open: false, msg: '', sev: 'success' });

  const onChange = (field) => (e) => {
    const value = e.target.type === 'checkbox' ? e.target.checked : e.target.value;
    setForm((f) => ({ ...f, [field]: value }));
  };
  const onHP = (field) => (e) => {
    setForm((f) => ({ ...f, handlingParameter: { ...(f.handlingParameter || {}), [field]: e.target.value } }));
  };

  // Image handling functions
  const handleImageUpload = (e) => {
    const files = Array.from(e.target.files);
    files.forEach(file => {
      if (!file.type.startsWith('image/')) return;
      const reader = new FileReader();
      reader.onload = (evt) => {
        setImages(prev => [...prev, {
          name: file.name,
          dataUrl: evt.target.result,
          isPrimary: prev.length === 0 // First image is primary
        }]);
      };
      reader.readAsDataURL(file);
    });
    e.target.value = ''; // Reset input
  };

  const removeImage = (index) => {
    setImages(prev => {
      const updated = prev.filter((_, i) => i !== index);
      // If we removed the primary image, make the first remaining image primary
      if (prev[index]?.isPrimary && updated.length > 0) {
        updated[0].isPrimary = true;
      }
      return updated;
    });
  };

  const setPrimaryImage = (index) => {
    setImages(prev => prev.map((img, i) => ({
      ...img,
      isPrimary: i === index
    })));
  };

  const handleAutoFill = () => {
    const unique = Math.floor(Math.random() * 1000);
    setForm({
      materialCode: `MAT-${unique}`,
      materialName: `Auto Material ${unique}`,
      description: 'Auto-generated material for testing',
      packagingTypes: ['Global'],
      packagingMaterials: ['Carton'],
      skus: [{ name: `SKU-${unique}-Base`, type: 'Bottle' }],
      countryOfOrigin: 'USA',
      type: TYPES[0],
      materialClass: CLASSES[0],
      materialGroup: GROUPS[0],
      materialState: STATES[0],
      baseUOM: 'EA',
      netWeightKg: 0.5,
      netWeightUom: 'KG',
      lengthMM: 50,
      widthMM: 50,
      heightMM: 150,
      dimensionUom: 'MM',
      shelfLifeDays: 730,
      materialEANupc: `EAN-${unique}`,
      upc: `UPC-${unique}`,
      storageType: STORAGE_TYPES[0],
      procurementType: PROCUREMENT_TYPES[0],
      vehicleType: VEHICLE_TYPES[0],
      tradeUOM: 'EA',
      tradeWeightKg: 6,
      tradeWeightUom: 'KG',
      tradeLengthMM: 180,
      tradeWidthMM: 180,
      tradeHeightMM: 150,
      tradeDimensionUom: 'MM',
      isPackaged: true,
      isFragile: false,
      isHighValue: false,
      isEnvSensitive: false,
      isBatchManaged: true,
      isSerialized: false,
      handlingParameter: {
        temperatureMin: 10,
        temperatureMax: 25,
        humidityMin: 30,
        humidityMax: 60,
        hazardousClass: 'None',
        epcFormat: 'URN',
        envParameters: 'Keep Dry',
        precautions: 'Handle with care',
      },
    });
  };

  const valid = useMemo(() => {
    return (
      form.materialCode.trim() &&
      form.materialName.trim() &&
      form.type &&
      form.materialClass &&
      form.materialGroup &&
      form.baseUOM
    );
  }, [form]);

  const stepValid = useMemo(() => {
    switch (activeStep) {
      case 0:
        return form.materialCode.trim() && form.materialName.trim() && form.type && form.materialClass && form.materialGroup;
      case 1:
        return !!form.baseUOM;
      case 2:
        return true;
      case 3:
        return true; 
      case 4: 
        return true;
      case 5: // Images - optional
        return true;
      case 6: // Flags
        return true;
      case 7: // Review
        return valid;
      default:
        return true;
    }
  }, [activeStep, form, valid]);

  const submit = async () => {
    if (!valid) {
      setToast({ open: true, msg: 'Please complete all required fields.', sev: 'error' });
      return;
    }
    setSaving(true);
    try {
      const payload = {
        code: form.materialCode,
        name: form.materialName,
        description: form.description,
        type: form.type,
        category: form.materialGroup,
        baseUom: form.baseUOM,

        isBatchManaged: form.isBatchManaged,
        isSerialManaged: form.isSerialized,

        shelfLifeDays: form.shelfLifeDays ? Number(form.shelfLifeDays) : null,
        minStock: 0,
        maxStock: 0,

        grossWeight: form.tradeWeightKg ? Number(form.tradeWeightKg) : null,
        netWeight: form.netWeightKg ? Number(form.netWeightKg) : null,
        weightUom: form.netWeightUom || 'KG', // Form handles weight in chosen UOM

        length: form.lengthMM ? Number(form.lengthMM) : null,
        width: form.widthMM ? Number(form.widthMM) : null,
        height: form.heightMM ? Number(form.heightMM) : null,
        dimensionUom: form.dimensionUom || 'MM',

        isHazmat: form.handlingParameter.hazardousClass && form.handlingParameter.hazardousClass !== 'None',
        hazmatClass: form.handlingParameter.hazardousClass,
        unNumber: null, // No field in form
        packagingTypes: form.packagingTypes,
        packagingMaterials: form.packagingMaterials,
        skus: form.skus,

        status: 'ACTIVE'
      };

      await MaterialsAPI.create(payload);
      setToast({ open: true, msg: 'Material created', sev: 'success' });
      // Short delay to allow toast to be seen before navigation or just nav
      setTimeout(() => navigate(`/materials`), 1000);
    } catch (e) {
      console.error(e);
      setToast({ open: true, msg: e?.response?.data?.message || e.message || 'Create failed', sev: 'error' });
    } finally {
      setSaving(false);
    }
  };

  return (
    <Paper elevation={0} sx={{ p: 2 }}>
      <Box sx={{ mb: 2, display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
        <Typography variant="h6" sx={{ fontWeight: 700 }}>Create Material</Typography>
        <Button startIcon={<AutoFixHigh />} onClick={handleAutoFill} color="secondary">Auto-Fill</Button>
      </Box>

      <Stepper activeStep={activeStep} alternativeLabel sx={{ mb: 3 }}>
        {STEPS.map(label => (
          <Step key={label}><StepLabel>{label}</StepLabel></Step>
        ))}
      </Stepper>

      {activeStep === 0 && (
        <Paper variant="outlined" sx={{ p: 2, mb: 2 }}>
          <Typography variant="subtitle1" sx={{ fontWeight: 700, mb: 1 }}>General</Typography>
          <Grid container spacing={2}>
            <Grid item xs={6}><TextField label="Material Code" required fullWidth size="small" value={form.materialCode} onChange={onChange('materialCode')} /></Grid>
            <Grid item xs={6}><TextField label="Material Name" required fullWidth size="small" value={form.materialName} onChange={onChange('materialName')} /></Grid>
            <Grid item xs={12}><TextField label="Description" multiline minRows={2} fullWidth size="small" value={form.description} onChange={onChange('description')} /></Grid>
            <Grid item xs={6}><TextField label="Country of Origin" fullWidth size="small" value={form.countryOfOrigin} onChange={onChange('countryOfOrigin')} /></Grid>
            <Grid item xs={6}><TextField select label="Material Type" required fullWidth size="small" value={form.type} onChange={onChange('type')}>{TYPES.map(t => <MenuItem key={t} value={t}>{t}</MenuItem>)}</TextField></Grid>
            <Grid item xs={6}><TextField select label="Material State" fullWidth size="small" value={form.materialState} onChange={onChange('materialState')}>{STATES.map(t => <MenuItem key={t} value={t}>{t}</MenuItem>)}</TextField></Grid>
            <Grid item xs={6}><TextField select label="Material Class" required fullWidth size="small" value={form.materialClass} onChange={onChange('materialClass')}>{CLASSES.map(t => <MenuItem key={t} value={t}>{t}</MenuItem>)}</TextField></Grid>
            <Grid item xs={6}><TextField select label="Material Group" required fullWidth size="small" value={form.materialGroup} onChange={onChange('materialGroup')}>{GROUPS.map(t => <MenuItem key={t} value={t}>{t}</MenuItem>)}</TextField></Grid>
          </Grid>
        </Paper>
      )}

      {activeStep === 1 && (
        <Paper variant="outlined" sx={{ p: 2, mb: 2 }}>
          <Typography variant="subtitle1" sx={{ fontWeight: 700, mb: 1 }}>Dimensions & Weight</Typography>
          <Grid container spacing={2}>
            {/* Base */}
            <Grid item xs={12}><Typography variant="subtitle2" color="text.secondary" sx={{ mb: -1 }}>Base Specification</Typography></Grid>
            <Grid item xs={3}><TextField select label="Base UOM" required fullWidth size="small" value={form.baseUOM} onChange={onChange('baseUOM')}>{UOMS.map(t => <MenuItem key={t} value={t}>{t}</MenuItem>)}</TextField></Grid>
            <Grid item xs={3}><TextField type="number" label="Net Weight" fullWidth size="small" value={form.netWeightKg} onChange={onChange('netWeightKg')} /></Grid>
            <Grid item xs={2}><TextField select label="Weight UOM" fullWidth size="small" value={form.netWeightUom} onChange={onChange('netWeightUom')}>{UOMS.map(t => <MenuItem key={t} value={t}>{t}</MenuItem>)}</TextField></Grid>
            <Grid item xs={4} />
            <Grid item xs={3}><TextField type="number" label="Length" fullWidth size="small" value={form.lengthMM} onChange={onChange('lengthMM')} /></Grid>
            <Grid item xs={3}><TextField type="number" label="Width" fullWidth size="small" value={form.widthMM} onChange={onChange('widthMM')} /></Grid>
            <Grid item xs={3}><TextField type="number" label="Height" fullWidth size="small" value={form.heightMM} onChange={onChange('heightMM')} /></Grid>
            <Grid item xs={3}>
               <TextField select label="Dim UOM" fullWidth size="small" value={form.dimensionUom} onChange={onChange('dimensionUom')}>
                   <MenuItem value="MM">MM</MenuItem>
                   <MenuItem value="CM">CM</MenuItem>
                   <MenuItem value="IN">IN</MenuItem>
                   <MenuItem value="M">M</MenuItem>
               </TextField>
            </Grid>

            {/* Trade */}
            <Grid item xs={12}><Typography variant="subtitle2" color="text.secondary" sx={{ mt: 1, mb: -1 }}>Trade Specification</Typography></Grid>
            <Grid item xs={3}><TextField select label="Trade UOM" fullWidth size="small" value={form.tradeUOM} onChange={onChange('tradeUOM')}>{UOMS.map(t => <MenuItem key={t} value={t}>{t}</MenuItem>)}</TextField></Grid>
            <Grid item xs={3}><TextField type="number" label="Trade Weight" fullWidth size="small" value={form.tradeWeightKg} onChange={onChange('tradeWeightKg')} /></Grid>
            <Grid item xs={2}><TextField select label="Weight UOM" fullWidth size="small" value={form.tradeWeightUom} onChange={onChange('tradeWeightUom')}>{UOMS.map(t => <MenuItem key={t} value={t}>{t}</MenuItem>)}</TextField></Grid>
            <Grid item xs={4} />
            <Grid item xs={3}><TextField type="number" label="Trade Length" fullWidth size="small" value={form.tradeLengthMM} onChange={onChange('tradeLengthMM')} /></Grid>
            <Grid item xs={3}><TextField type="number" label="Trade Width" fullWidth size="small" value={form.tradeWidthMM} onChange={onChange('tradeWidthMM')} /></Grid>
            <Grid item xs={3}><TextField type="number" label="Trade Height" fullWidth size="small" value={form.tradeHeightMM} onChange={onChange('tradeHeightMM')} /></Grid>
            <Grid item xs={3}>
               <TextField select label="Trade Dim UOM" fullWidth size="small" value={form.tradeDimensionUom} onChange={onChange('tradeDimensionUom')}>
                   <MenuItem value="MM">MM</MenuItem>
                   <MenuItem value="CM">CM</MenuItem>
                   <MenuItem value="IN">IN</MenuItem>
                   <MenuItem value="M">M</MenuItem>
               </TextField>
            </Grid>
          </Grid>
        </Paper>
      )}

      {activeStep === 2 && (
        <Paper variant="outlined" sx={{ p: 2, mb: 2 }}>
          <Typography variant="subtitle1" sx={{ fontWeight: 700, mb: 1 }}>Storage & Handling</Typography>
          <Grid container spacing={2}>
            <Grid item xs={3}><TextField type="number" label="Shelf Life (days)" fullWidth size="small" value={form.shelfLifeDays} onChange={onChange('shelfLifeDays')} /></Grid>
            <Grid item xs={3}><TextField select label="Storage Type" fullWidth size="small" value={form.storageType} onChange={onChange('storageType')}>{STORAGE_TYPES.map(t => <MenuItem key={t} value={t}>{t}</MenuItem>)}</TextField></Grid>
            <Grid item xs={3}><TextField select label="Procurement Type" fullWidth size="small" value={form.procurementType} onChange={onChange('procurementType')}>{PROCUREMENT_TYPES.map(t => <MenuItem key={t} value={t}>{t}</MenuItem>)}</TextField></Grid>
            <Grid item xs={3}><TextField select label="Vehicle Type" fullWidth size="small" value={form.vehicleType} onChange={onChange('vehicleType')}>{VEHICLE_TYPES.map(t => <MenuItem key={t} value={t}>{t}</MenuItem>)}</TextField></Grid>
            <Grid item xs={6}><TextField type="number" label="Temp Min (°C)" fullWidth size="small" value={form.handlingParameter.temperatureMin} onChange={onHP('temperatureMin')} /></Grid>
            <Grid item xs={6}><TextField type="number" label="Temp Max (°C)" fullWidth size="small" value={form.handlingParameter.temperatureMax} onChange={onHP('temperatureMax')} /></Grid>
            <Grid item xs={6}><TextField type="number" label="Humidity Min (%)" fullWidth size="small" value={form.handlingParameter.humidityMin} onChange={onHP('humidityMin')} /></Grid>
            <Grid item xs={6}><TextField type="number" label="Humidity Max (%)" fullWidth size="small" value={form.handlingParameter.humidityMax} onChange={onHP('humidityMax')} /></Grid>
            <Grid item xs={6}><TextField label="Hazardous Class" fullWidth size="small" value={form.handlingParameter.hazardousClass} onChange={onHP('hazardousClass')} /></Grid>
            <Grid item xs={6}><TextField label="EPC Format" fullWidth size="small" value={form.handlingParameter.epcFormat} onChange={onHP('epcFormat')} /></Grid>
            <Grid item xs={12}><TextField label="Environment Parameters" fullWidth size="small" value={form.handlingParameter.envParameters} onChange={onHP('envParameters')} /></Grid>
            <Grid item xs={12}><TextField label="Precautions" fullWidth size="small" value={form.handlingParameter.precautions} onChange={onHP('precautions')} /></Grid>
          </Grid>
        </Paper>
      )}

      {activeStep === 3 && (
        <Paper variant="outlined" sx={{ p: 2, mb: 2 }}>
          <Typography variant="subtitle1" sx={{ fontWeight: 700, mb: 1 }}>Packaging Settings</Typography>
          <Grid container spacing={2}>
            <Grid item xs={12}>
              <Autocomplete
                multiple
                freeSolo
                options={['Global', 'Economy', 'Standard', 'Premium', 'Value Pack']}
                value={form.packagingTypes}
                onChange={(e, newValue) => setForm(f => ({ ...f, packagingTypes: newValue }))}
                renderTags={(value, getTagProps) =>
                  value.map((option, index) => (
                    <Chip variant="outlined" label={option} size="small" {...getTagProps({ index })} />
                  ))
                }
                renderInput={(params) => <TextField {...params} label="Packaging Types" placeholder="Type and press Enter" size="small" />}
              />
            </Grid>
            <Grid item xs={12}>
              <Autocomplete
                multiple
                freeSolo
                options={['Carton', 'Box', 'Wooden Crate', 'Premium Wrap']}
                value={form.packagingMaterials}
                onChange={(e, newValue) => setForm(f => ({ ...f, packagingMaterials: newValue }))}
                renderTags={(value, getTagProps) =>
                  value.map((option, index) => (
                    <Chip variant="outlined" label={option} size="small" {...getTagProps({ index })} />
                  ))
                }
                renderInput={(params) => <TextField {...params} label="Packaging Materials" placeholder="Type and press Enter" size="small" />}
              />
            </Grid>
            <Grid item xs={12}>
              <Box sx={{ mt: 2, display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                <Typography variant="subtitle2" color="text.secondary">SKU Configurations</Typography>
                <Button size="small" startIcon={<Add />} onClick={() => setForm(f => ({ ...f, skus: [...(f.skus || []), { name: '', type: '' }] }))}>Add SKU</Button>
              </Box>
              {(form.skus || []).map((sku, index) => (
                <Box key={index} sx={{ display: 'flex', gap: 2, mt: 1, alignItems: 'flex-start' }}>
                  <TextField label="SKU Name" size="small" fullWidth value={sku.name} onChange={e => {
                    const newSkus = [...form.skus];
                    newSkus[index].name = e.target.value;
                    setForm(f => ({ ...f, skus: newSkus }));
                  }} />
                  <TextField label="SKU Type" size="small" fullWidth value={sku.type} onChange={e => {
                    const newSkus = [...form.skus];
                    newSkus[index].type = e.target.value;
                    setForm(f => ({ ...f, skus: newSkus }));
                  }} />
                  <IconButton color="error" onClick={() => {
                    const newSkus = [...form.skus];
                    newSkus.splice(index, 1);
                    setForm(f => ({ ...f, skus: newSkus }));
                  }}><Delete /></IconButton>
                </Box>
              ))}
            </Grid>
          </Grid>
        </Paper>
      )}

      {activeStep === 4 && (
        <Paper variant="outlined" sx={{ p: 2, mb: 2 }}>
          <Typography variant="subtitle1" sx={{ fontWeight: 700, mb: 1 }}>Identifiers</Typography>
          <Grid container spacing={2}>
            <Grid item xs={6}><TextField label="Material EAN/UPC" fullWidth size="small" value={form.materialEANupc} onChange={onChange('materialEANupc')} /></Grid>
            <Grid item xs={6}><TextField label="UPC" fullWidth size="small" value={form.upc} onChange={onChange('upc')} /></Grid>
            <Grid item xs={6}><TextField label="External ERP Code" fullWidth size="small" value={form.externalERPCode || ''} onChange={onChange('externalERPCode')} /></Grid>
            <Grid item xs={6}><TextField label="Packaging Material Code" fullWidth size="small" value={form.packagingMaterialCode || ''} onChange={onChange('packagingMaterialCode')} /></Grid>
          </Grid>
        </Paper>
      )}

      {activeStep === 5 && (
        <Paper variant="outlined" sx={{ p: 2, mb: 2 }}>
          <Typography variant="subtitle1" sx={{ fontWeight: 700, mb: 1 }}>
            <ImageIcon sx={{ mr: 1, verticalAlign: 'middle' }} />
            Product Images
          </Typography>
          <Typography variant="body2" color="text.secondary" sx={{ mb: 2 }}>
            Upload images of the material. The first image will be set as the primary image.
          </Typography>

          <input
            type="file"
            ref={fileInputRef}
            hidden
            accept="image/*"
            multiple
            onChange={handleImageUpload}
          />

          <Button
            variant="outlined"
            startIcon={<CloudUpload />}
            onClick={() => fileInputRef.current?.click()}
            sx={{ mb: 2 }}
          >
            Upload Images
          </Button>

          {images.length > 0 ? (
            <Grid container spacing={2}>
              {images.map((img, index) => (
                <Grid item xs={6} sm={4} md={3} key={index}>
                  <Card variant="outlined" sx={{ position: 'relative' }}>
                    {img.isPrimary && (
                      <Box
                        sx={{
                          position: 'absolute',
                          top: 8,
                          left: 8,
                          bgcolor: 'primary.main',
                          color: 'white',
                          px: 1,
                          py: 0.25,
                          borderRadius: 1,
                          fontSize: '0.7rem',
                          fontWeight: 'bold',
                          zIndex: 1
                        }}
                      >
                        PRIMARY
                      </Box>
                    )}
                    <CardMedia
                      component="img"
                      height="120"
                      image={img.dataUrl}
                      alt={img.name}
                      sx={{ objectFit: 'cover' }}
                    />
                    <CardActions sx={{ justifyContent: 'space-between', py: 0.5 }}>
                      <Tooltip title="Set as primary">
                        <IconButton
                          size="small"
                          onClick={() => setPrimaryImage(index)}
                          disabled={img.isPrimary}
                          color={img.isPrimary ? 'primary' : 'default'}
                        >
                          <ImageIcon fontSize="small" />
                        </IconButton>
                      </Tooltip>
                      <Tooltip title="Remove">
                        <IconButton
                          size="small"
                          onClick={() => removeImage(index)}
                          color="error"
                        >
                          <Delete fontSize="small" />
                        </IconButton>
                      </Tooltip>
                    </CardActions>
                  </Card>
                </Grid>
              ))}
            </Grid>
          ) : (
            <Alert severity="info">No images uploaded. You can add images or skip this step.</Alert>
          )}
        </Paper>
      )}

      {activeStep === 6 && (
        <Paper variant="outlined" sx={{ p: 2, mb: 2 }}>
          <Typography variant="subtitle1" sx={{ fontWeight: 700, mb: 1 }}>Flags</Typography>
          <Grid container>
            <Grid item xs={12}>
              <FormControlLabel control={<Checkbox checked={!!form.isPackaged} onChange={onChange('isPackaged')} />} label="Packaged Material" />
              <FormControlLabel control={<Checkbox checked={!!form.isFragile} onChange={onChange('isFragile')} />} label="Fragile Material" />
              <FormControlLabel control={<Checkbox checked={!!form.isHighValue} onChange={onChange('isHighValue')} />} label="High Value" />
              <FormControlLabel control={<Checkbox checked={!!form.isEnvSensitive} onChange={onChange('isEnvSensitive')} />} label="Environment Sensitive" />
              <FormControlLabel control={<Checkbox checked={!!form.isBatchManaged} onChange={onChange('isBatchManaged')} />} label="Batch Material" />
              <FormControlLabel control={<Checkbox checked={!!form.isSerialized} onChange={onChange('isSerialized')} />} label="Serialized" />
            </Grid>
          </Grid>
        </Paper>
      )}

      {activeStep === 7 && (
        <Paper variant="outlined" sx={{ p: 2, mb: 2 }}>
          <Typography variant="subtitle1" sx={{ fontWeight: 700, mb: 1 }}>Review</Typography>
          <MaterialDetailCard material={form} images={images.map(i => i.dataUrl)} />
        </Paper>
      )}

      <Box sx={{ display: 'flex', justifyContent: 'space-between', mt: 1 }}>
        <Button disabled={activeStep === 0} onClick={() => setActiveStep(s => Math.max(0, s - 1))}>Back</Button>
        <Box sx={{ display: 'flex', gap: 1 }}>
          {activeStep < 7 && (
            <Button variant="contained" onClick={() => setActiveStep(s => s + 1)} disabled={!stepValid}>Next</Button>
          )}
          {activeStep === 7 && (
            <>
              <Button variant="outlined" onClick={() => setPreviewOpen(true)} disabled={!valid}>Preview</Button>
              <Button variant="contained" onClick={submit} disabled={!valid || saving}>{saving ? 'Saving...' : 'Submit'}</Button>
            </>
          )}
        </Box>
      </Box>

      <Dialog open={previewOpen} onClose={() => setPreviewOpen(false)} maxWidth="lg" fullWidth>
        <DialogTitle>Preview</DialogTitle>
        <DialogContent>
          <MaterialDetailCard material={form} images={images.map(i => i.dataUrl)} />
        </DialogContent>
        <DialogActions>
          <Button onClick={() => setPreviewOpen(false)}>Close</Button>
        </DialogActions>
      </Dialog>

      <Snackbar open={toast.open} autoHideDuration={3000} onClose={() => setToast(t => ({ ...t, open: false }))}>
        <Alert severity={toast.sev} sx={{ width: '100%' }}>{toast.msg}</Alert>
      </Snackbar>
    </Paper>
  );
}
