// ilms-frontend/src/components/LabelManagement/MaterialInventory.jsx
import React, { useState, useEffect } from 'react';
import {
    Box, Button, Paper, Typography, Grid,
    Table, TableBody, TableCell, TableContainer, TableHead, TableRow,
    Chip, TextField, InputAdornment, IconButton, Switch, FormControlLabel,
    Tooltip, LinearProgress, Checkbox, Menu, MenuItem, Divider
} from '@mui/material';
import { 
    Search, Print, Refresh, 
    CheckCircle, Error as ErrorIcon, 
    FilterList, Inventory2, LocationOn,
    ArrowDropDown, CheckBox as CheckBoxIcon,
    CheckBoxOutlineBlank
} from '@mui/icons-material';
import { InventoryAPI } from '../../services/APIService';
import { useNavigate } from 'react-router-dom';

export default function MaterialInventory() {
    const navigate = useNavigate();
    const [inventory, setInventory] = useState([]);
    const [loading, setLoading] = useState(false);
    const [searchQuery, setSearchQuery] = useState('');
    const [showUnprintedOnly, setShowUnprintedOnly] = useState(false);
    
    // Selection State
    const [selectedIds, setSelectedIds] = useState([]);
    const [anchorEl, setAnchorEl] = useState(null);

    useEffect(() => {
        loadInventory();
    }, []);

    const loadInventory = async () => {
        setLoading(true);
        try {
            const data = await InventoryAPI.list();
            setInventory(data);
            setSelectedIds([]); // Reset selection on reload
        } catch (e) {
            console.error("Failed to load inventory", e);
        }
        setLoading(false);
    };

    const filteredInventory = inventory.filter(item => {
        const matchesSearch = 
            item.serialNumber?.toLowerCase().includes(searchQuery.toLowerCase()) ||
            item.materialName?.toLowerCase().includes(searchQuery.toLowerCase()) ||
            item.batchNumber?.toLowerCase().includes(searchQuery.toLowerCase());
        
        const matchesFilter = showUnprintedOnly ? item.labelPrinted === 'N' : true;
        
        return matchesSearch && matchesFilter;
    });

    const passItems = filteredInventory.filter(item => item.qualityStatus === 'PASS');

    // Selection Handlers
    const handleToggleSelect = (id, status) => {
        if (status !== 'PASS') return; // Strict QC Check
        setSelectedIds(prev => 
            prev.includes(id) ? prev.filter(i => i !== id) : [...prev, id]
        );
    };

    const handleSelectAllPass = () => {
        const passIds = passItems.map(i => i.id);
        setSelectedIds(passIds);
        setAnchorEl(null);
    };

    const handleSelectByBatch = (batch) => {
        const batchPassIds = passItems.filter(i => i.batchNumber === batch).map(i => i.id);
        setSelectedIds(prev => Array.from(new Set([...prev, ...batchPassIds])));
        setAnchorEl(null);
    };

    const handleSelectByProduct = (productCode) => {
        const prodPassIds = passItems.filter(i => i.materialCode === productCode).map(i => i.id);
        setSelectedIds(prev => Array.from(new Set([...prev, ...prodPassIds])));
        setAnchorEl(null);
    };

    const handleClearSelection = () => {
        setSelectedIds([]);
        setAnchorEl(null);
    };

    const handleBulkPrint = () => {
        if (selectedIds.length === 0) return;
        // Collect full objects for the selected IDs to pass to print station
        const selectedItems = inventory.filter(i => selectedIds.includes(i.id));
        navigate('/labels/trade-print', { state: { preSelectedItems: selectedItems } });
    };

    // Derived Data for Menus
    const uniqueBatches = Array.from(new Set(passItems.map(i => i.batchNumber)));
    const uniqueProducts = Array.from(new Set(passItems.map(i => i.materialName)));

    return (
        <Box sx={{ p: 3 }}>
            {/* Header Area */}
            <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', mb: 3 }}>
                <Box>
                    <Typography variant="h4" fontWeight="bold" sx={{ display: 'flex', alignItems: 'center', gap: 1.5 }}>
                        <Inventory2 color="primary" /> Material Inventory
                    </Typography>
                    <Typography variant="body2" color="text.secondary">
                        QC-Verified Label Management & Serialization Tracking
                    </Typography>
                </Box>
                <Box sx={{ display: 'flex', gap: 2 }}>
                    <Button 
                        startIcon={<Refresh />} 
                        onClick={loadInventory} 
                        disabled={loading}
                        variant="outlined"
                        sx={{ borderRadius: 2 }}
                    >
                        Refresh Data
                    </Button>
                    <Button
                        variant="contained"
                        startIcon={<Print />}
                        disabled={selectedIds.length === 0}
                        onClick={handleBulkPrint}
                        sx={{ 
                            borderRadius: 2, 
                            px: 3, 
                            bgcolor: 'primary.main',
                            '&:hover': { bgcolor: 'primary.dark' },
                            boxShadow: '0 4px 14px 0 rgba(0,118,255,0.39)'
                        }}
                    >
                        Print Selected ({selectedIds.length})
                    </Button>
                </Box>
            </Box>

            {/* Selection Toolbar */}
            <Paper variant="outlined" sx={{ p: 1.5, mb: 2, bgcolor: '#f8fafc', display: 'flex', alignItems: 'center', gap: 2, borderRadius: 2 }}>
                <Button
                    size="small"
                    variant="text"
                    startIcon={<CheckBoxIcon />}
                    endIcon={<ArrowDropDown />}
                    onClick={(e) => setAnchorEl(e.currentTarget)}
                    sx={{ textTransform: 'none', fontWeight: 'bold' }}
                >
                    Selection Options
                </Button>
                <Menu
                    anchorEl={anchorEl}
                    open={Boolean(anchorEl)}
                    onClose={() => setAnchorEl(null)}
                >
                    <MenuItem onClick={handleSelectAllPass}>Select All (QC PASS Only)</MenuItem>
                    <Divider />
                    <Box sx={{ px: 2, py: 1 }}><Typography variant="caption" color="text.secondary" fontWeight="bold">SELECT BY BATCH</Typography></Box>
                    {uniqueBatches.map(b => (
                        <MenuItem key={b} onClick={() => handleSelectByBatch(b)}>Batch: {b}</MenuItem>
                    ))}
                    <Divider />
                    <Box sx={{ px: 2, py: 1 }}><Typography variant="caption" color="text.secondary" fontWeight="bold">SELECT BY PRODUCT</Typography></Box>
                    {uniqueProducts.map(p => (
                        <MenuItem key={p} onClick={() => handleSelectByProduct(inventory.find(i => i.materialName === p)?.materialCode)}>
                           {p}
                        </MenuItem>
                    ))}
                    <Divider />
                    <MenuItem onClick={handleClearSelection} sx={{ color: 'error.main' }}>Clear Selection</MenuItem>
                </Menu>

                <Divider orientation="vertical" flexItem sx={{ mx: 1 }} />
                
                <TextField
                    placeholder="Search Serial, Material or Batch..."
                    size="small"
                    value={searchQuery}
                    onChange={(e) => setSearchQuery(e.target.value)}
                    sx={{ width: 350, bgcolor: 'white' }}
                    InputProps={{
                        startAdornment: (
                            <InputAdornment position="start">
                                <Search scale={0.8} />
                            </InputAdornment>
                        ),
                    }}
                />
                
                <FormControlLabel
                    control={
                        <Switch 
                            size="small"
                            checked={showUnprintedOnly} 
                            onChange={(e) => setShowUnprintedOnly(e.target.checked)}
                        />
                    }
                    label={<Typography variant="body2">Unprinted Only</Typography>}
                    sx={{ ml: 1 }}
                />

                <Box sx={{ flex: 1 }} />
                
                <Typography variant="caption" color="text.secondary" sx={{ mr: 2 }}>
                    <b>{selectedIds.length}</b> items selected of <b>{passItems.length}</b> eligible
                </Typography>
            </Paper>

            {loading && <LinearProgress sx={{ mb: 2, borderRadius: 1 }} />}

            {/* Inventory Table */}
            <TableContainer component={Paper} variant="outlined" sx={{ borderRadius: 3, overflow: 'hidden' }}>
                <Table stickyHeader size="small">
                    <TableHead>
                        <TableRow>
                            <TableCell padding="checkbox" sx={{ bgcolor: 'grey.50' }}>
                                <Checkbox
                                    size="small"
                                    indeterminate={selectedIds.length > 0 && selectedIds.length < passItems.length}
                                    checked={passItems.length > 0 && selectedIds.length === passItems.length}
                                    onChange={(e) => {
                                        if (e.target.checked) handleSelectAllPass();
                                        else handleClearSelection();
                                    }}
                                />
                            </TableCell>
                            <TableCell sx={{ fontWeight: 'bold', bgcolor: 'grey.50' }}>Serial Number</TableCell>
                            <TableCell sx={{ fontWeight: 'bold', bgcolor: 'grey.50' }}>Material Details</TableCell>
                            <TableCell sx={{ fontWeight: 'bold', bgcolor: 'grey.50' }}>Batch / Lot</TableCell>
                            <TableCell sx={{ fontWeight: 'bold', bgcolor: 'grey.50' }}>Quality Status</TableCell>
                            <TableCell sx={{ fontWeight: 'bold', bgcolor: 'grey.50' }} align="center">Label Printed</TableCell>
                            <TableCell sx={{ fontWeight: 'bold', bgcolor: 'grey.50' }}>Location</TableCell>
                        </TableRow>
                    </TableHead>
                    <TableBody>
                        {filteredInventory.length > 0 ? (
                            filteredInventory.map((item) => {
                                const isSelected = selectedIds.includes(item.id);
                                const isEligible = item.qualityStatus === 'PASS';
                                
                                return (
                                    <TableRow 
                                        key={item.id} 
                                        hover 
                                        selected={isSelected}
                                        onClick={() => isEligible && handleToggleSelect(item.id, item.qualityStatus)}
                                        sx={{ cursor: isEligible ? 'pointer' : 'default', '&:hover': { bgcolor: isEligible ? 'action.hover' : 'inherit' } }}
                                    >
                                        <TableCell padding="checkbox">
                                            <Tooltip title={!isEligible ? "Cannot select items requiring QC clearance" : ""}>
                                                <span>
                                                    <Checkbox
                                                        size="small"
                                                        checked={isSelected}
                                                        disabled={!isEligible}
                                                        onChange={() => handleToggleSelect(item.id, item.qualityStatus)}
                                                        onClick={(e) => e.stopPropagation()}
                                                    />
                                                </span>
                                            </Tooltip>
                                        </TableCell>
                                        <TableCell>
                                            <Typography variant="body2" sx={{ fontFamily: 'monospace', fontWeight: 600 }}>
                                                {item.serialNumber}
                                            </Typography>
                                        </TableCell>
                                        <TableCell>
                                            <Typography variant="body2" fontWeight="bold">
                                                {item.materialName}
                                            </Typography>
                                            <Typography variant="caption" color="text.secondary">
                                                Code: {item.materialCode}
                                            </Typography>
                                        </TableCell>
                                        <TableCell>
                                            <Chip 
                                                label={item.batchNumber} 
                                                size="small" 
                                                variant="outlined" 
                                                sx={{ borderRadius: 1 }}
                                            />
                                        </TableCell>
                                        <TableCell>
                                            <Chip 
                                                label={item.qualityStatus}
                                                size="small"
                                                color={item.qualityStatus === 'PASS' ? 'success' : item.qualityStatus === 'HOLD' ? 'warning' : 'error'}
                                                sx={{ fontWeight: 500, fontSize: '0.7rem' }}
                                            />
                                        </TableCell>
                                        <TableCell align="center">
                                            <Chip 
                                                label={item.labelPrinted === 'Y' ? 'YES' : 'NO'}
                                                color={item.labelPrinted === 'Y' ? 'success' : 'default'}
                                                size="small"
                                                variant={item.labelPrinted === 'Y' ? 'filled' : 'outlined'}
                                                sx={{ minWidth: 50 }}
                                            />
                                        </TableCell>
                                        <TableCell>
                                            <Box sx={{ display: 'flex', alignItems: 'center', gap: 0.5 }}>
                                                <LocationOn sx={{ fontSize: 16, color: 'text.secondary' }} />
                                                <Typography variant="caption">
                                                    {item.locationName || 'N/A'}
                                                </Typography>
                                            </Box>
                                        </TableCell>
                                    </TableRow>
                                );
                            })
                        ) : (
                            <TableRow>
                                <TableCell colSpan={7} align="center" sx={{ py: 8 }}>
                                    <Box sx={{ opacity: 0.5 }}>
                                        <Inventory2 sx={{ fontSize: 48, mb: 1 }} />
                                        <Typography variant="h6">No eligible inventory found</Typography>
                                        <Typography variant="body2">
                                            Only QC Pass materials are eligible for label printing
                                        </Typography>
                                    </Box>
                                </TableCell>
                            </TableRow>
                        )}
                    </TableBody>
                </Table>
            </TableContainer>
        </Box>
    );
}

// ilms-frontend-angular/src/app/components/material-inventory/material-inventory.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { MatTableModule } from '@angular/material/table';
import { MatCheckboxModule } from '@angular/material/checkbox';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatInputModule } from '@angular/material/input';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatChipsModule } from '@angular/material/chips';
import { MatProgressBarModule } from '@angular/material/progress-bar';
import { MatMenuModule } from '@angular/material/menu';
import { MatTooltipModule } from '@angular/material/tooltip';
import { MatSlideToggleModule } from '@angular/material/slide-toggle';
import { ApiService } from '../../services/api.service';

@Component({
  selector: 'app-material-inventory',
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    MatTableModule,
    MatCheckboxModule,
    MatButtonModule,
    MatIconModule,
    MatInputModule,
    MatFormFieldModule,
    MatChipsModule,
    MatProgressBarModule,
    MatMenuModule,
    MatTooltipModule,
    MatSlideToggleModule
  ],
  templateUrl: './material-inventory.component.html',
  styleUrl: './material-inventory.component.scss'
})
export class MaterialInventoryComponent implements OnInit {
  inventory: any[] = [];
  filteredInventory: any[] = [];
  loading = false;
  searchQuery = '';
  showUnprintedOnly = false;
  selectedIds = new Set<string>();

  displayedColumns: string[] = ['select', 'serialNumber', 'materialDetails', 'batchNumber', 'qualityStatus', 'labelPrinted', 'location'];

  constructor(private apiService: ApiService, private router: Router) {}

  ngOnInit() {
    this.loadInventory();
  }

  async loadInventory() {
    this.loading = true;
    try {
      this.inventory = await this.apiService.getInventory();
      this.applyFilters();
    } catch (e) {
      console.error(e);
    } finally {
      this.loading = false;
    }
  }

  applyFilters() {
    this.filteredInventory = this.inventory.filter(item => {
      const matchesSearch = 
        item.serialNumber?.toLowerCase().includes(this.searchQuery.toLowerCase()) ||
        item.materialName?.toLowerCase().includes(this.searchQuery.toLowerCase()) ||
        item.batchNumber?.toLowerCase().includes(this.searchQuery.toLowerCase());
      
      const matchesFilter = this.showUnprintedOnly ? item.labelPrinted === 'N' : true;
      
      return matchesSearch && matchesFilter;
    });
  }

  get passItems() {
    return this.filteredInventory.filter(item => item.qualityStatus === 'PASS');
  }

  isAllSelected() {
    const numSelected = this.selectedIds.size;
    const numRows = this.passItems.length;
    return numSelected === numRows && numRows > 0;
  }

  masterToggle() {
    if (this.isAllSelected()) {
      this.selectedIds.clear();
    } else {
      this.passItems.forEach(row => this.selectedIds.add(row.id));
    }
  }

  toggleRow(row: any) {
    if (row.qualityStatus !== 'PASS') return;
    if (this.selectedIds.has(row.id)) {
      this.selectedIds.delete(row.id);
    } else {
      this.selectedIds.add(row.id);
    }
  }

  selectByBatch(batch: string) {
    this.passItems
      .filter(item => item.batchNumber === batch)
      .forEach(item => this.selectedIds.add(item.id));
  }

  selectByProduct(productName: string) {
    this.passItems
      .filter(item => item.materialName === productName)
      .forEach(item => this.selectedIds.add(item.id));
  }

  clearSelection() {
    this.selectedIds.clear();
  }

  get uniqueBatches() {
    return Array.from(new Set(this.passItems.map(i => i.batchNumber)));
  }

  get uniqueProducts() {
    return Array.from(new Set(this.passItems.map(i => i.materialName)));
  }

  handleBulkPrint() {
    if (this.selectedIds.size === 0) return;
    const selectedItems = this.inventory.filter(i => this.selectedIds.has(i.id));
    this.router.navigate(['/labels/trade-print'], { state: { preSelectedItems: selectedItems } });
  }
}

<div class="inventory-container">
  <div class="header-area">
    <div class="header-left">
      <h1 class="title">
        <mat-icon color="primary">inventory_2</mat-icon> Material Inventory
      </h1>
      <p class="subtitle">QC-Verified Label Management & Serialization Tracking</p>
    </div>
    <div class="header-right">
      <button mat-stroked-button (click)="loadInventory()" [disabled]="loading">
        <mat-icon>refresh</mat-icon> Refresh Data
      </button>
      <button mat-flat-button color="primary" [disabled]="selectedIds.size === 0" (click)="handleBulkPrint()" class="print-btn">
        <mat-icon>print</mat-icon> Print Selected ({{selectedIds.size}})
      </button>
    </div>
  </div>

  <mat-card class="toolbar-card">
    <div class="toolbar-left">
      <button mat-button [matMenuTriggerFor]="selectionMenu" class="selection-btn">
        <mat-icon>check_box</mat-icon> Selection Options <mat-icon>arrow_drop_down</mat-icon>
      </button>
      <mat-menu #selectionMenu="matMenu">
        <button mat-menu-item (click)="masterToggle()">Select All (QC PASS Only)</button>
        <div class="menu-label">SELECT BY BATCH</div>
        <button mat-menu-item *ngFor="let b of uniqueBatches" (click)="selectByBatch(b)">Batch: {{b}}</button>
        <div class="menu-label">SELECT BY PRODUCT</div>
        <button mat-menu-item *ngFor="let p of uniqueProducts" (click)="selectByProduct(p)">{{p}}</button>
        <mat-divider></mat-divider>
        <button mat-menu-item (click)="clearSelection()" class="text-warn">Clear Selection</button>
      </mat-menu>

      <mat-divider vertical></mat-divider>

      <mat-form-field appearance="outline" class="search-field">
        <mat-icon matPrefix>search</mat-icon>
        <input matInput placeholder="Search Serial, Material or Batch..." [(ngModel)]="searchQuery" (ngModelChange)="applyFilters()">
      </mat-form-field>

      <mat-slide-toggle [(ngModel)]="showUnprintedOnly" (change)="applyFilters()">
        Unprinted Only
      </mat-slide-toggle>
    </div>
    <div class="toolbar-right">
      <span class="selection-info">
        <b>{{selectedIds.size}}</b> items selected of <b>{{passItems.length}}</b> eligible
      </span>
    </div>
  </mat-card>

  <mat-progress-bar mode="indeterminate" *ngIf="loading"></mat-progress-bar>

  <div class="table-container mui-card">
    <table mat-table [dataSource]="filteredInventory" class="inventory-table">
      <!-- Checkbox Column -->
      <ng-container matColumnDef="select">
        <th mat-header-cell *matHeaderCellDef>
          <mat-checkbox (change)="$event ? masterToggle() : null"
                        [checked]="isAllSelected()"
                        [indeterminate]="selectedIds.size > 0 && !isAllSelected()">
          </mat-checkbox>
        </th>
        <td mat-cell *matCellDef="let row">
          <mat-checkbox (click)="$event.stopPropagation()"
                        (change)="$event ? toggleRow(row) : null"
                        [checked]="selectedIds.has(row.id)"
                        [disabled]="row.qualityStatus !== 'PASS'"
                        [matTooltip]="row.qualityStatus !== 'PASS' ? 'Cannot select items requiring QC clearance' : ''">
          </mat-checkbox>
        </td>
      </ng-container>

      <ng-container matColumnDef="serialNumber">
        <th mat-header-cell *matHeaderCellDef> Serial Number </th>
        <td mat-cell *matCellDef="let row" class="mono-font">{{row.serialNumber}}</td>
      </ng-container>

      <ng-container matColumnDef="materialDetails">
        <th mat-header-cell *matHeaderCellDef> Material Details </th>
        <td mat-cell *matCellDef="let row">
          <div class="material-info">
            <span class="name">{{row.materialName}}</span>
            <span class="code">Code: {{row.materialCode}}</span>
          </div>
        </td>
      </ng-container>

      <ng-container matColumnDef="batchNumber">
        <th mat-header-cell *matHeaderCellDef> Batch / Lot </th>
        <td mat-cell *matCellDef="let row">
          <span class="batch-chip">{{row.batchNumber}}</span>
        </td>
      </ng-container>

      <ng-container matColumnDef="qualityStatus">
        <th mat-header-cell *matHeaderCellDef> Quality Status </th>
        <td mat-cell *matCellDef="let row">
          <span class="status-chip" [ngClass]="row.qualityStatus.toLowerCase()">
            {{row.qualityStatus}}
          </span>
        </td>
      </ng-container>

      <ng-container matColumnDef="labelPrinted">
        <th mat-header-cell *matHeaderCellDef> Label Printed </th>
        <td mat-cell *matCellDef="let row">
          <span class="print-chip" [class.printed]="row.labelPrinted === 'Y'">
            {{row.labelPrinted === 'Y' ? 'YES' : 'NO'}}
          </span>
        </td>
      </ng-container>

      <ng-container matColumnDef="location">
        <th mat-header-cell *matHeaderCellDef> Location </th>
        <td mat-cell *matCellDef="let row">
          <div class="location-info">
            <mat-icon>location_on</mat-icon>
            {{row.locationName || 'N/A'}}
          </div>
        </td>
      </ng-container>

      <tr mat-header-row *matHeaderRowDef="displayedColumns"></tr>
      <tr mat-row *matRowDef="let row; columns: displayedColumns;" 
          (click)="toggleRow(row)"
          [class.selected-row]="selectedIds.has(row.id)"
          [class.disabled-row]="row.qualityStatus !== 'PASS'"></tr>
    </table>

    <div class="no-data" *ngIf="!loading && filteredInventory.length === 0">
      <mat-icon>inventory_2</mat-icon>
      <h3>No eligible inventory found</h3>
      <p>Only QC Pass materials are eligible for label printing</p>
    </div>
  </div>
</div>
